### ISSUE TITLE
Twitter example not working?

### ISSUE THREAD

**Issue by dougmcclure** [LucidWorks/spark-solr#10]
System using solr 5.1 solrCloud. Created collection using one of the samples in 5.1 - solr-5.1.0/server/solr/configsets/data_driven_schema_configs/conf/.

Set up my twitter API stuff and launched:

./spark-submit --master local[2] --class com.lucidworks.spark.SparkApp /opt/sparkSolr/spark-solr-master/target/spark-solr-1.0-SNAPSHOT.jar twitter-to-solr -zkHost=foo.com:12181 -collection=SparkTwitter2
2015-05-07 08:26:08,553 [main] INFO  SparkApp  - Running processor twitter-to-solr
2015-05-07 08:26:09,237 [main] WARN  NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-05-07 08:26:10,049 [sparkDriver-akka.actor.default-dispatcher-7] INFO  Slf4jLogger  - Slf4jLogger started
2015-05-07 08:26:10,118 [sparkDriver-akka.actor.default-dispatcher-7] INFO  Remoting  - Starting remoting
2015-05-07 08:26:10,336 [sparkDriver-akka.actor.default-dispatcher-7] INFO  Remoting  - Remoting started; listening on addresses :[akka.tcp://sparkDriver@foo.com:42899]
2015-05-07 08:26:10,618 [main] INFO  Server  - jetty-8.y.z-SNAPSHOT
2015-05-07 08:26:10,639 [main] INFO  AbstractConnector  - Started SocketConnector@0.0.0.0:36168
2015-05-07 08:26:10,836 [main] INFO  Server  - jetty-8.y.z-SNAPSHOT
2015-05-07 08:26:10,866 [main] INFO  AbstractConnector  - Started SelectChannelConnector@0.0.0.0:4040
2015-05-07 08:26:13,427 [Twitter Stream consumer-1[initializing]] INFO  TwitterStreamImpl  - Establishing connection.
2015-05-07 08:26:14,833 [Twitter Stream consumer-1[Establishing connection]] INFO  TwitterStreamImpl  - Connection established.
2015-05-07 08:26:14,834 [Twitter Stream consumer-1[Establishing connection]] INFO  TwitterStreamImpl  - Receiving status stream.
2015-05-07 08:26:16,145 [Executor task launch worker-1] INFO  SolrZkClient  - Using default ZkCredentialsProvider
2015-05-07 08:26:16,179 [Executor task launch worker-1] INFO  ConnectionManager  - Waiting for client to connect to ZooKeeper
2015-05-07 08:26:16,195 [zkCallback-2-thread-1] INFO  ConnectionManager  - Watcher org.apache.solr.common.cloud.ConnectionManager@473b5792 name:ZooKeeperConnection Watcher:foo.com:12181 got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2015-05-07 08:26:16,195 [Executor task launch worker-1] INFO  ConnectionManager  - Client is connected to ZooKeeper
2015-05-07 08:26:16,195 [Executor task launch worker-1] INFO  SolrZkClient  - Using default ZkACLProvider
2015-05-07 08:26:16,197 [Executor task launch worker-1] INFO  ZkStateReader  - Updating cluster state from ZooKeeper...

<sits here until I kill it>

Launched the Spark GUI and see all kinds of completed jobs, stages, and batches processed.  No apparent failures. I run a query in the Solr Admin UI and don't have any results in my collection.

What should I look for here?

Tks!

**Comment by thelabdude** [comment]
SolrSupport doesn't send commits from Spark, rather it relies on auto-commits to be configured for your collection. Please check your solrconfig.xml to make sure you've configured auto commits, which are disabled by default in Solr unfortunately (I tried to make them enabled but somebody changed that code). For twitter, maybe do something like:

     <autoCommit> 
       <maxDocs>50000</maxDocs>
       <openSearcher>false</openSearcher> 
     </autoCommit>
     <autoSoftCommit> 
       <maxTime>3000</maxTime> 
     </autoSoftCommit>

**Comment by dougmcclure** [comment]
I've configured collections using the examples in Solr 5.1:

./zkcli.sh -cmd upconfig -zkhost localhost:12181 -c SparkTwitter2 -confname
SparkTwitter2 -solrhome solr-5.1.0/server/solr -confdir
solr-5.1.0/server/solr/configsets/data_driven_schema_configs/conf/

From what I can see in each solrconfig.xml, those auto commit settings are
there.

in data_driven_schema_configs:

 <autoCommit>
      <maxTime>15000</maxTime>
      <openSearcher>false</openSearcher>
    </autoCommit>

    <!--
      <autoSoftCommit>
        <maxTime>1000</maxTime>
      </autoSoftCommit>


So, this time I ran the submit job and it worked and I have tweets in a
collection.

{ "id": "tweet-596320138049114112", "provider_s": "twitter", "author_s":
"yu_c92EDHsXikQ7", "type_s": "post", "_indexed_at_tdt":
"2015-05-07T14:26:16.273Z", "_version_": 1500521459157565400 },


Let's see if I can query:

./spark-submit --master local[2] --class com.lucidworks.spark.SparkApp
/opt/sparkSolr/spark-solr-master/target/spark-solr-1.0-SNAPSHOT.jar
query-solr -zkHost=nc9098037068.tivlab.austin.ibm.com:12181
-collection=SparkTwitter2 -query="*:*"


15/05/21 13:20:09 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
java.lang.RuntimeException:
org.apache.solr.client.solrj.SolrServerException:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error
10.0.0.1 server at http://10.0.0.1:8983/solr/SparkTwitter2_shard1_replica1:
sort param field can't be found: timestamp
        at
com.lucidworks.spark.query.PagedResultsIterator.hasNext(PagedResultsIterator.java:54)
        at
scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at
org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:202)
        at
org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:56)
        at
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        at
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at
org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.client.solrj.SolrServerException:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error
10.0.0.1 server at http://10.0.0.1:8983/solr/SparkTwitter2_shard1_replica1:
sort param field can't be found: timestamp
        at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:473)
        at
com.lucidworks.spark.query.PagedResultsIterator.fetchNextPage(PagedResultsIterator.java:73)
        at
com.lucidworks.spark.query.PagedResultsIterator.hasNext(PagedResultsIterator.java:50)
        ... 13 more
Caused by:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error
10.0.0.1 server at http://10.0.0.1:8983/solr/SparkTwitter2_shard1_replica1:
sort param field can't be found: timestamp
        at
org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:556)
        at
org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:233)
        at
org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:225)
        at
org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135)
        at
org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)
        at
org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)
        at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:444)
        ... 15 more
15/05/21 13:20:09 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1,
localhost): java.lang.RuntimeException:
org.apache.solr.client.solrj.SolrServerException:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error
10.0.0.1 server at http://10.0.0.1:8983/solr/SparkTwitter2_shard1_replica1:
sort param field can't be found: timestamp
        at
com.lucidworks.spark.query.PagedResultsIterator.hasNext(PagedResultsIterator.java:54)
        at
scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at
org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:202)
        at
org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:56)
        at
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        at
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at
org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.client.solrj.SolrServerException:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error
10.0.0.1 server at http://10.0.0.1:8983/solr/SparkTwitter2_shard1_replica1:
sort param field can't be found: timestamp
        at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:473)
        at
com.lucidworks.spark.query.PagedResultsIterator.fetchNextPage(PagedResultsIterator.java:73)
        at
com.lucidworks.spark.query.PagedResultsIterator.hasNext(PagedResultsIterator.java:50)
        ... 13 more
Caused by:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error
10.0.0.1 server at http://10.0.0.1:8983/solr/SparkTwitter2_shard1_replica1:
sort param field can't be found: timestamp
        at
org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:556)
        at
org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:233)
        at
org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:225)
        at
org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135)
        at
org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)
        at
org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)
        at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:444)
        ... 15 more

15/05/21 13:20:09 ERROR TaskSetManager: Task 1 in stage 0.0 failed 1 times;
aborting job




Are you expecting different fields to be in the collection? It looks like
you're looking for a timestamp field to sort on.

Tks!

Doug

**Comment by thelabdude** [comment]
Looks like your soft-commit is still commented out? 

Can you make sure you've pulled the latest code? There's no mention of "timestamp" anywhere in the code base ... I just ran against the latest code and Solr 5.1 and the query-solr action works correctly for me:

output should be something like this:

: 2264
[rt: 727
http://t: 668
]: 249
a: 210
to: 177
de: 168
the: 164
you: 129
i: 118
que: 106
https://t: 101
and: 94
me: 91
la: 90
for: 83
of: 76
in: 76
en: 71
is: 68
# of echos : [725]

**Comment by dougmcclure** [comment]
Ok, I rebuilt with your latest and the query job runs and terminates. In my
console output I eventually see:

# of echos : [32454]

Should I see anything else - a breakout of all types, users ?  Looks like
your output has some sort of word count?

I'd like to hit some other collections I have via spark-shell.  What's an
example of that look like?

Doug

**Comment by thelabdude** [comment]
Hi Doug,

Glad you got it working after an update ... Take a look at the QueryProcessor.java code to see what that example does.

I don't have an example of using this lib from the Spark shell, but would be good to have that. I'll cook something up over the weekend.

Cheers,
Tim

**Comment by thelabdude** [comment]
Just posted some code and README updates to help with interacting with Solr from the spark-shell, please take a look.

**Comment by dougmcclure** [comment]
Ok, this works well for a single collection.  In my environment, I have daily collections being created and I use a collection alias to give me one collection name to interact with. It doesn't appear that the spark-solr code supports this collection alias or the Solr API queries you're passing don't find the collection alias.

5/05/27 13:35:34 INFO ZkStateReader: Updating cluster state from ZooKeeper...
java.lang.IllegalArgumentException: Collection doug not found!
        at com.lucidworks.spark.SolrRDD.buildShardList(SolrRDD.java:393)
        at com.lucidworks.spark.SolrRDD.queryShards(SolrRDD.java:235)
        at com.lucidworks.spark.SolrRDD.query(SolrRDD.java:226)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:24)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:29)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:31)
        at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:33)
        at $iwC$$iwC$$iwC$$iwC.<init>(<console>:35)
        at $iwC$$iwC$$iwC.<init>(<console>:37)
        at $iwC$$iwC.<init>(<console>:39)
        at $iwC.<init>(<console>:41)
        at <init>(<console>:43)
        at .<init>(<console>:47)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1338)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
        at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:856)
        at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:901)
        at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:813)
        at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:656)
        at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:664)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:669)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:996)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:944)
        at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:944)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:944)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1058)
        at org.apache.spark.repl.Main$.main(Main.scala:31)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by thelabdude** [comment]
No the code doesn't support collection aliases yet, but that's fairly easy to add ... give me a few minutes and I'll push out an update (just need to write a unit test for that)

**Comment by thelabdude** [comment]
Ok, fixed the buildShardList method to support collection aliases as well. Thanks for letting me know about this issue ;-)

**Comment by thelabdude** [comment]
Any update on this? I'll close the ticket for now, open a new one if you have more questions / issues. Thanks.
