### ISSUE TITLE
Issue while writing to solr using Spark 1.6 and Solr 6.3

### ISSUE THREAD

**Issue by nitingithub** [lucidworks/spark-solr#109]
Exception in thread "main" java.lang.AbstractMethodError: solr.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/DataFrame;)Lorg/apache/spark/sql/sources/BaseRelation;
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)

Any help on this is much appreciated. I am using the latest version of the spark solr lib using gradle dependency

**Comment by kiranchitturi** [comment]
For Spark 1.6.x, you should the 2.x.x release line instead of the latest 3.x line

Can you try this http://search.maven.org/#artifactdetails%7Ccom.lucidworks.spark%7Cspark-solr%7C2.2.3%7Cjar

**Comment by kiranchitturi** [comment]
We are coming up a new 2.3 release that supports Solr 6.3 and Spark 1.6.x

**Comment by nitingithub** [comment]
Thanks. Tried with 2.x and it works.
