### ISSUE TITLE
Twitter example not working

### ISSUE THREAD

**Issue by Abhi002** [LucidWorks/spark-solr#11]
hduser@abhi-VirtualBox:~$ /usr/local/spark/bin/spark-submit --master local[2] --class com.lucidworks.spark.SparkApp  spark-solr-1.0-SNAPSHOT.jar twitter-to-solr -zkHost localhost:9983 -collection collection1
2015-05-26 17:01:39,459 [main] INFO  SparkApp  - Running processor twitter-to-solr
2015-05-26 17:01:40,134 [main] WARN  Utils  - Your hostname, abhi-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.10.10.241 instead (on interface eth0)
2015-05-26 17:01:40,137 [main] WARN  Utils  - Set SPARK_LOCAL_IP if you need to bind to another address
2015-05-26 17:01:46,469 [main] WARN  NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-05-26 17:01:48,498 [sparkDriver-akka.actor.default-dispatcher-3] INFO  Slf4jLogger  - Slf4jLogger started
2015-05-26 17:01:48,694 [sparkDriver-akka.actor.default-dispatcher-3] INFO  Remoting  - Starting remoting
2015-05-26 17:01:49,416 [sparkDriver-akka.actor.default-dispatcher-3] INFO  Remoting  - Remoting started; listening on addresses :[akka.tcp://sparkDriver@10.10.10.241:49486]
2015-05-26 17:01:50,165 [main] INFO  Server  - jetty-8.y.z-SNAPSHOT
2015-05-26 17:01:50,241 [main] INFO  AbstractConnector  - Started SocketConnector@0.0.0.0:50090
2015-05-26 17:01:52,682 [main] INFO  Server  - jetty-8.y.z-SNAPSHOT
2015-05-26 17:01:52,706 [main] INFO  AbstractConnector  - Started SelectChannelConnector@0.0.0.0:4040
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/streaming/twitter/TwitterUtils
        at com.lucidworks.spark.example.streaming.TwitterToSolrStreamProcessor.plan(TwitterToSolrStreamProcessor.java:36)
        at com.lucidworks.spark.SparkApp$StreamProcessor.run(SparkApp.java:77)
        at com.lucidworks.spark.SparkApp.main(SparkApp.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.streaming.twitter.TwitterUtils
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 12 more

I have spark 1.3.1, solr 5.1.0 and hadoop 2.6. Please help

**Comment by thelabdude** [comment]
how did you build your job jar? looks like you're missing classes
