### ISSUE TITLE
Using spark-solr 2.3.0 (or 2.3.1)

### ISSUE THREAD

**Issue by lujea** [lucidworks/spark-solr#117]
Hi I am having some classpath errors when using the latests spark-solr. Note that I am using a Solr 6.2.1

This is the scala code: 
val solr_collection_name = "ma"
val zk_connect_string = "10.10.23.247:32000/solr"

var options = Map("collection" -> "ma","zkhost" -> "10.10.23.247:32000/solr", "request_handler" -> "/export","splits" -> "true", "split_field" -> "id", "use_cursor_mark" -> "true", "query" -> "documenttype:message", "fields" -> "id,msgid,documenttype,ownerstr,senderdomainstr,recipientdomainstr")

var solrData = spark.read.format("solr").options(options).load()

The code breaks when trying to load the data from solr with the following error:

java.lang.ClassNotFoundException: Detected an incompatible DataSourceRegister. Please remove the incompatible library from classpath or upgrade it. Error: org.apache.spark.sql.sources.DataSourceRegister: Provider org.apache.spark.ml.source.libsvm.DefaultSource could not be instantiated
  at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:179)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:79)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:79)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
  ... 48 elided
Caused by: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider org.apache.spark.ml.source.libsvm.DefaultSource could not be instantiated
  at java.util.ServiceLoader.fail(ServiceLoader.java:232)
  at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
  at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
  at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
  at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
  at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
  at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
  at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:128)
  ... 53 more
Caused by: java.lang.NoClassDefFoundError: org/apache/spark/Logging
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  at java.lang.Class.getConstructor0(Class.java:3075)
  at java.lang.Class.newInstance(Class.java:412)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
  ... 64 more
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Logging
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 80 more

**Comment by lujea** [comment]
Note that I am using spark 2.0.1 with hadoop 2.6. Can you please tell me if I should use a different version of spark solr or if I am missing some dependencies ?

**Comment by kiranchitturi** [comment]
@lujea you should be using the [3.0.0-alpha.2](http://search.maven.org/#artifactdetails%7Ccom.lucidworks.spark%7Cspark-solr%7C3.0.0-alpha.2%7Cjar) version.

spark-solr 2.3.x works with Spark 1.6.x and 3.0.x works with Spark 2.0.1

**Comment by lujea** [comment]
thanks @kiranchitturi

**Comment by imranrajjad** [comment]
this happened with spark 2.1.0 using 3.0.0.beta3 on windows

scala> val col1 = sqlContext.load("solr",Map("zkHost" -> "localhost:9983/solr","collection" -> "col1"))
warning: there was one deprecation warning; re-run with -deprecation for details
java.lang.ClassNotFoundException: Failed to find data source: solr. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:549)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:301)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
  at org.apache.spark.sql.SQLContext.load(SQLContext.scala:957)
  ... 48 elided
Caused by: java.lang.ClassNotFoundException: solr.DefaultSource
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:62)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21$$anonfun$apply$12.apply(DataSource.scala:533)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21$$anonfun$apply$12.apply(DataSource.scala:533)
  at scala.util.Try$.apply(Try.scala:192)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21.apply(DataSource.scala:533)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21.apply(DataSource.scala:533)
  at scala.util.Try.orElse(Try.scala:84)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:533)
  ... 54 more

on Linux it works but some collections return empty empty schema

**Comment by kiranchitturi** [comment]
that is really odd. Are you invoking the spark-shell with shaded jar?

**Comment by kiranchitturi** [comment]
Also, please open a new issue instead of commenting on older issues

**Comment by rashid-1989** [comment]
@imranrajjad 
I am also getting the same exception with spark 2.3.1, Solr 7.3.0 and spark-solr 3.5.5 (latest).
Did you have any luck resolving it?

**Comment by manuhortet** [comment]
Same with Spark 2.3.1, Solr 7.4.0 and spark-solr 3.5.5
