### ISSUE TITLE
NullPointer when trying to get a uniqueKey

### ISSUE THREAD

**Issue by dale-chang91** [lucidworks/spark-solr#129]
Hi guys,

First I would like to thank you with all the work you have been doing. I really appreciate it.

Stack info:
Spark 2.0.0.1.something (We are using the HDP 2.5.2 stack)
Scala 2.11.8
Java 1.8
Spark-Solr 2.3.4

When I try and do SolrJavaRDD.get(zkhosts, collection, sc), the code goes and tries to instantiate a SolrRDD from Scala code. However, it throws a NullPointer when it tries to get or create a unique key.

Stack trace: 
java.lang.NullPointerException
	at com.lucidworks.spark.rdd.SolrRDD.<init>(SolrRDD.scala:33)
	at com.lucidworks.spark.rdd.SolrRDD$.apply(SolrRDD.scala:223)
	at com.lucidworks.spark.rdd.SolrJavaRDD.get(SolrJavaRDD.java:49)

Code at line 33 (spark-solr version 2.3.4):
val uniqueKey = if (uKey.isDefined) uKey.get else SolrQuerySupport.getUniqueKey(zkHost, collection.split(",")(0))

uKey is an Option[None], and I don't specify it, so it goes to SolrQuerySupport, I believe...

I have made sure that the zkhosts, collection, SparkContext are not null. Any help would be great

**Comment by kiranchitturi** [comment]
Please check https://github.com/LucidWorks/spark-solr#version-compatibility

You should be using 3.0.0-alpha.2 spark-solr

**Comment by dale-chang91** [comment]
I switched to 3.0.0-alpha.2 and I still get the same problem

**Comment by kiranchitturi** [comment]
Hmm, we have a test method where just passing zkHost, collectionName, SC works https://github.com/LucidWorks/spark-solr/blob/2.4.0/src/test/java/com/lucidworks/spark/SolrRDDTest.java#L65

Are you sure the variables you pass in are not null ?

**Comment by dale-chang91** [comment]
Well that's embarassing... I have made sure they are not null now.

I would hate to ask you to solve a non-Lucidworks Spark-Solr issue for me, but I am thinking that there are multiple versions of jars or maybe an absent jar causing this error

17/03/15 11:15:11 ERROR ApplicationMaster: User class threw exception: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.apache.solr.client.solrj.impl.HttpClientUtil.getConfigurer()Lorg/apache/solr/client/solrj/impl/HttpClientConfigurer;
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.apache.solr.client.solrj.impl.HttpClientUtil.getConfigurer()Lorg/apache/solr/client/solrj/impl/HttpClientConfigurer;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at com.lucidworks.spark.util.SolrSupport$.getCachedCloudClient(SolrSupport.scala:93)
	at com.lucidworks.spark.util.SolrSupport$.getSolrBaseUrl(SolrSupport.scala:97)
	at com.lucidworks.spark.util.SolrQuerySupport$.getUniqueKey(SolrQuerySupport.scala:82)
	at com.lucidworks.spark.rdd.SolrRDD.<init>(SolrRDD.scala:34)
	at com.lucidworks.spark.rdd.SolrRDD$.apply(SolrRDD.scala:194)
	at com.lucidworks.spark.rdd.SolrJavaRDD.get(SolrJavaRDD.java:45)
	at cobra.analytics.util.tfidf.TFIDFUtil.getTFIDFFromQuery(TFIDFUtil.java:108)
	at cobra.analytics.TAR.test.TARSVMTest.main(TARSVMTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:627)
Caused by: java.lang.NoSuchMethodError: org.apache.solr.client.solrj.impl.HttpClientUtil.getConfigurer()Lorg/apache/solr/client/solrj/impl/HttpClientConfigurer;
	at com.lucidworks.spark.util.SolrSupport$.setupKerberosIfNeeded(SolrSupport.scala:64)
	at com.lucidworks.spark.util.SolrSupport$.getSolrCloudClient(SolrSupport.scala:81)
	at com.lucidworks.spark.util.SolrSupport$.getNewSolrCloudClient(SolrSupport.scala:89)
	at com.lucidworks.spark.util.CacheSolrClient$$anon$1.load(SolrSupport.scala:38)
	at com.lucidworks.spark.util.CacheSolrClient$$anon$1.load(SolrSupport.scala:36)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)

**Comment by kiranchitturi** [comment]
This must be version conflicts within the libraries. Take a look at our pom.xml https://github.com/lucidworks/spark-solr/blob/master/pom.xml to see what dependencies we use

Your application probably has some libraries that are in conflict with the libraries spark-solr uses. You would have to manage your dependencies by excluding them or shading

**Comment by dale-chang91** [comment]
I was afraid you would say that. Thanks for all of your help. I'll mark this as closed
