### ISSUE TITLE
ERROR StreamingResultsIterator when querying documents with childdocuments

### ISSUE THREAD

**Issue by baosiek** [lucidworks/spark-solr#163]
The following error seems to be a consequence of https://issues.apache.org/jira/browse/SOLR-7557 (still open) at SolrQuerySupport.scala.

Partial StackTrace is: 
java.lang.RuntimeException: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr3:8983/solr/momnutch_shard2_replica2: parsing error
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:89)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1760)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1158)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1158)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr3:8983/solr/momnutch_shard2_replica2: parsing error
	at com.lucidworks.spark.util.SolrQuerySupport$.querySolr(SolrQuerySupport.scala:216)
	at com.lucidworks.spark.util.SolrQuerySupport.querySolr(SolrQuerySupport.scala)
	at com.lucidworks.spark.query.StreamingResultsIterator.fetchNextPage(StreamingResultsIterator.java:114)
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:82)

**Comment by kiranchitturi** [comment]
Could you provide the query and full stacktrace?

**Comment by baosiek** [comment]
Initial Query:
q=id:"http://180graus.com/agua-branca"&fl=[child+parentFilter%3Did:"http://180graus.com/agua-branca"]*&collection=momnutch1 uniqueKey = id

SolrQuerySupport$  - Added default sort clause on uniqueKey field id to query 
[stacktrace.txt](https://github.com/lucidworks/spark-solr/files/1177858/stacktrace.txt)
[stacktrace.txt](https://github.com/lucidworks/spark-solr/files/1177860/stacktrace.txt)

q=id:"http://180graus.com/agua-branca"&fl=[child+parentFilter%3Did:"http://180graus.com/agua-branca"]*&collection=momnutch1&distrib=false&start=0&rows=5000&sort=id+asc

Full StackTrace
=============

2017-07-26 19:41:17,953 [main] WARN  NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-07-26 19:41:18,589 [main] INFO  log  - Logging initialized @1568ms
2017-07-26 19:41:18,686 [main] INFO  Server  - jetty-9.2.z-SNAPSHOT
2017-07-26 19:41:18,706 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@6b5176f2{/jobs,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,706 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@b672aa8{/jobs/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,706 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@2fab4aff{/jobs/job,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,707 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@ec0c838{/jobs/job/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,707 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@6e46d9f4{/stages,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,707 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@5cc69cfe{/stages/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,707 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@29cfd92b{/stages/stage,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,708 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@21c64522{/stages/stage/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,708 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@7997b197{/stages/pool,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,708 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@11dee337{/stages/pool/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,708 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@460f76a6{/storage,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,709 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@55f3c410{/storage/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,709 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@11acdc30{/storage/rdd,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,709 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@770d4269{/storage/rdd/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,709 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@4a8ab068{/environment,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,710 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@1922e6d{/environment/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,710 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@76a82f33{/executors,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,710 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@6bab2585{/executors/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,710 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@74bdc168{/executors/threadDump,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,711 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@644c78d4{/executors/threadDump/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,719 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@532a02d9{/static,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,719 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@611f8234{/,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,720 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@7bb3a9fe{/api,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,720 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@7cbee484{/jobs/job/kill,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,721 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@7f811d00{/stages/stage/kill,null,AVAILABLE,@Spark}
2017-07-26 19:41:18,730 [main] INFO  ServerConnector  - Started Spark@1b11ef33{HTTP/1.1}{0.0.0.0:4040}
2017-07-26 19:41:18,730 [main] INFO  Server  - Started @1711ms
2017-07-26 19:41:19,038 [main] INFO  ContextHandler  - Started o.s.j.s.ServletContextHandler@430fa4ef{/metrics/json,null,AVAILABLE,@Spark}
2017-07-26 19:41:20,053 [main] INFO  SelectSolrRDD  - rq = /select, setting query defaults for query = q=id:"http://180graus.com/agua-branca"&fl=[child+parentFilter%3Did:"http://180graus.com/agua-branca"]*&collection=momnutch1 uniqueKey = id
2017-07-26 19:41:20,053 [main] INFO  SolrQuerySupport$  - Added default sort clause on uniqueKey field id to query q=id:"http://180graus.com/agua-branca"&fl=[child+parentFilter%3Did:"http://180graus.com/agua-branca"]*&collection=momnutch1&distrib=false&start=0&rows=5000&sort=id+asc
2017-07-26 19:41:20,084 [main] INFO  SelectSolrRDD  - Range filter added to the query: _version_:[* TO 1574001837060653056]
2017-07-26 19:41:20,085 [main] INFO  SelectSolrRDD  - Using splitField=None, splitsPerShard=None, and numReplicas=3 for computing partitions.
2017-07-26 19:41:20,085 [main] INFO  SelectSolrRDD  - Applied 6 intra-shard splits on the _version_ field for momnutch1 to better utilize all active replicas. Set the 'split_field' option to override this behavior or set the 'splits_per_shard' option = 1 to disable splits per shard.
2017-07-26 19:41:20,090 [main] INFO  SelectSolrRDD  - Found 18 partitions.
2017-07-26 19:41:22,164 [Executor task launch worker for task 0] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr1:8983/solr/momnutch1_shard1_replica1/ for partition 0
2017-07-26 19:41:22,212 [Executor task launch worker for task 1] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr2:8983/solr/momnutch1_shard1_replica2/ for partition 1
2017-07-26 19:41:22,251 [Executor task launch worker for task 2] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr3:8983/solr/momnutch1_shard1_replica3/ for partition 2
2017-07-26 19:41:22,272 [Executor task launch worker for task 3] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr1:8983/solr/momnutch1_shard1_replica1/ for partition 3
2017-07-26 19:41:22,299 [Executor task launch worker for task 4] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr2:8983/solr/momnutch1_shard1_replica2/ for partition 4
2017-07-26 19:41:22,322 [Executor task launch worker for task 5] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr3:8983/solr/momnutch1_shard1_replica3/ for partition 5
2017-07-26 19:41:22,347 [Executor task launch worker for task 6] ERROR SolrQuerySupport$  - Query [q=id:"http://180graus.com/agua-branca"&fl=[child+parentFilter%3Did:"http://180graus.com/agua-branca"]*&collection=momnutch1&distrib=false&start=0&rows=5000&sort=id+asc&fq=_version_:[*+TO+1574001837060653056]&fq={!hash+workers%3D6+worker%3D0}&partitionKeys=_version_&qt=/select&cursorMark=*] failed due to: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
2017-07-26 19:41:22,348 [Executor task launch worker for task 6] ERROR StreamingResultsIterator  - Fetch next page (0) from Solr http://tasks.solr1:8983/solr/momnutch1_shard2_replica1 using query [q=id:"http://180graus.com/agua-branca"&fl=[child+parentFilter%3Did:"http://180graus.com/agua-branca"]*&collection=momnutch1&distrib=false&start=0&rows=5000&sort=id+asc&fq=_version_:[*+TO+1574001837060653056]&fq={!hash+workers%3D6+worker%3D0}&partitionKeys=_version_&qt=/select&cursorMark=*], cursorMarks? true, cursorMarkOfCurrentPage=* failed due to: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
2017-07-26 19:41:22,348 [Executor task launch worker for task 6] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr1:8983/solr/momnutch1_shard2_replica1/ for partition 6
2017-07-26 19:41:22,352 [Executor task launch worker for task 6] ERROR Executor  - Exception in task 6.0 in stage 0.0 (TID 6)
java.lang.RuntimeException: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:89)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
	at com.lucidworks.spark.util.SolrQuerySupport$.querySolr(SolrQuerySupport.scala:216)
	at com.lucidworks.spark.util.SolrQuerySupport.querySolr(SolrQuerySupport.scala)
	at com.lucidworks.spark.query.StreamingResultsIterator.fetchNextPage(StreamingResultsIterator.java:114)
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:82)
	... 22 more
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:587)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:177)
	at com.lucidworks.spark.util.SolrQuerySupport$.queryAndStreamResponsePost(SolrQuerySupport.scala:154)
	at com.lucidworks.spark.util.SolrQuerySupport$.querySolr(SolrQuerySupport.scala:183)
	... 25 more
Caused by: org.apache.solr.common.SolrException: parsing error
	at org.apache.solr.client.solrj.impl.StreamingBinaryResponseParser.processResponse(StreamingBinaryResponseParser.java:88)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:585)
	... 31 more
Caused by: java.io.EOFException
	at org.apache.solr.common.util.FastInputStream.readByte(FastInputStream.java:207)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:250)
	at org.apache.solr.common.util.JavaBinCodec.readOrderedMap(JavaBinCodec.java:194)
	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:269)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:251)
	at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:173)
	at org.apache.solr.client.solrj.impl.StreamingBinaryResponseParser.processResponse(StreamingBinaryResponseParser.java:85)
	... 32 more
2017-07-26 19:41:22,393 [task-result-getter-2] WARN  TaskSetManager  - Lost task 6.0 in stage 0.0 (TID 6, localhost, executor driver): java.lang.RuntimeException: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:89)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
	at com.lucidworks.spark.util.SolrQuerySupport$.querySolr(SolrQuerySupport.scala:216)
	at com.lucidworks.spark.util.SolrQuerySupport.querySolr(SolrQuerySupport.scala)
	at com.lucidworks.spark.query.StreamingResultsIterator.fetchNextPage(StreamingResultsIterator.java:114)
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:82)
	... 22 more
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://tasks.solr1:8983/solr/momnutch1_shard2_replica1: parsing error
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:587)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:177)
	at com.lucidworks.spark.util.SolrQuerySupport$.queryAndStreamResponsePost(SolrQuerySupport.scala:154)
	at com.lucidworks.spark.util.SolrQuerySupport$.querySolr(SolrQuerySupport.scala:183)
	... 25 more
Caused by: org.apache.solr.common.SolrException: parsing error
	at org.apache.solr.client.solrj.impl.StreamingBinaryResponseParser.processResponse(StreamingBinaryResponseParser.java:88)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:585)
	... 31 more
Caused by: java.io.EOFException
	at org.apache.solr.common.util.FastInputStream.readByte(FastInputStream.java:207)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:250)
	at org.apache.solr.common.util.JavaBinCodec.readOrderedMap(JavaBinCodec.java:194)
	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:269)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:251)
	at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:173)
	at org.apache.solr.client.solrj.impl.StreamingBinaryResponseParser.processResponse(StreamingBinaryResponseParser.java:85)
	... 32 more

2017-07-26 19:41:22,404 [task-result-getter-2] ERROR TaskSetManager  - Task 6 in stage 0.0 failed 1 times; aborting job
2017-07-26 19:41:22,408 [Executor task launch worker for task 7] INFO  SelectSolrRDD  - Fetched 0 rows from shard http://tasks.solr2:8983/solr/momnutch1_shard2_replica2/ for partition 7
2017-07-26 19:42:19,537 [Thread-2] INFO  ServerConnector  - Stopped Spark@1b11ef33{HTTP/1.1}{0.0.0.0:4040}
2017-07-26 19:42:19,538 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@7f811d00{/stages/stage/kill,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@7cbee484{/jobs/job/kill,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@7bb3a9fe{/api,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@611f8234{/,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@532a02d9{/static,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@644c78d4{/executors/threadDump/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@74bdc168{/executors/threadDump,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@6bab2585{/executors/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@76a82f33{/executors,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,539 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@1922e6d{/environment/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@4a8ab068{/environment,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@770d4269{/storage/rdd/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@11acdc30{/storage/rdd,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@55f3c410{/storage/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@460f76a6{/storage,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@11dee337{/stages/pool/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@7997b197{/stages/pool,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,540 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@21c64522{/stages/stage/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@29cfd92b{/stages/stage,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@5cc69cfe{/stages/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@6e46d9f4{/stages,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@ec0c838{/jobs/job/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@2fab4aff{/jobs/job,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@b672aa8{/jobs/json,null,UNAVAILABLE,@Spark}
2017-07-26 19:42:19,541 [Thread-2] INFO  ContextHandler  - Stopped o.s.j.s.ServletContextHandler@6b5176f2{/jobs,null,UNAVAILABLE,@Spark}

**Comment by kiranchitturi** [comment]
@baosiek Have you figured out the issue?

If not, can you create a new issue with steps to reproduce? Thanks!
