### ISSUE TITLE
spark-solr maven conflict with spak-graph frames

### ISSUE THREAD

**Issue by imranrajjad** [lucidworks/spark-solr#169]
Greetings
My spark application requires to pull data from solr and convert into a graph frame for graph analysis purpose. Unfortunately, while resolving conflicts it has occurred that spark-solr and graphframes use the same `com.typesafe.scalalogging.Logger` class with different versions with spark-solr using 3.4.0 and graphframes using 2.1.2. Is there a way to compile spark-solr with 2.1.2 version since the source for graphframes is not available. below is the stack trace

```
java.lang.InstantiationError: com.typesafe.scalalogging.Logger
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:30)
	at com.typesafe.scalalogging.LazyLogging$class.logger(Logging.scala:28)
	at com.lucidworks.spark.util.SolrQuerySupport$.logger$lzycompute(SolrQuerySupport.scala:65)
	at com.lucidworks.spark.util.SolrQuerySupport$.logger(SolrQuerySupport.scala:65)
	at com.lucidworks.spark.util.SolrQuerySupport$.toQuery(SolrQuerySupport.scala:130)
	at com.lucidworks.spark.PartitionByTimeQueryParams.<init>(PartitionByTimeQueryParams.scala:50)
	at com.lucidworks.spark.SolrRelation.<init>(SolrRelation.scala:74)
	at com.lucidworks.spark.SolrRelation.<init>(SolrRelation.scala:47)
	at solr.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
	at com.elogic.callscoop.spark_test.AppTest.testSolr(AppTest.java:114
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

the maven dependencies

```
<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-hive-thriftserver_2.11</artifactId>
			<version>2.1.1</version>
		</dependency>

		<dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.11</artifactId>
        <version>2.1.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-graphx_2.11</artifactId>
        <version>2.1.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql_2.11</artifactId>
        <version>2.1.1</version>
    </dependency>
    <dependency>
        <groupId>graphframes</groupId>
        <artifactId>graphframes</artifactId>
        <version>0.5.0-spark2.1-s_2.11</version>
    </dependency>
		

	<dependency>
			<groupId>com.lucidworks.spark</groupId>
			<artifactId>spark-solr</artifactId>
			<version>3.1.0-ELOGIC</version>
			<exclusions>
				<exclusion>  
          			<groupId>com.fasterxml.jackson.core</groupId>
          			<artifactId>jackson-core</artifactId>
        		</exclusion>
        		<exclusion>  
          			<groupId>com.typesafe.scala-logging</groupId>
          			<artifactId>scala-logging-api_2.11</artifactId>          			
        		</exclusion>			
			</exclusions>
			
		</dependency>



		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
```

I tried to compile spark-solr with previous version of logging but it did not work. Any workaround will be appreciated

thanks
Imran

**Comment by kiranchitturi** [comment]
2.1.2 is a very old version of scala logging. It would require changes either in spark-solr to downgrade or in graphframes repo to upgrade to a latest version.  I don't see any use in downgrading scalalogging version for spark-solr.

This looks like the source code for graphframes https://github.com/graphframes/graphframes. Maybe it's worth upgrading graphframes to the latest version. I think they are aware of it as well (https://github.com/graphframes/graphframes/blob/master/build.sbt#L45) but stuck on older versions due to Spark 1.6 support (Scala 2.10)
