### ISSUE TITLE
SolrJ write failure

### ISSUE THREAD

**Issue by cheburakshu** [lucidworks/spark-solr#177]
Do you know why spark-solr fails like this?

```
>>> for table in tables:
...     parq = spark.read.parquet('/trick/{}'.format(table))
...     options = {
...         'zkhost' : 'localhost:2181/solr',
...         'collection' : table,
...         'gen_uniq_key' : 'true'
...     }
...     parq.write.format('solr').options(**options).mode('overwrite').save()
...
17/09/22 02:04:57 ERROR CloudSolrClient: Request to collection trick_log_visit failed due to (400) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI", retry? 0
17/09/22 02:04:57 ERROR SolrSupport$: Send batch to collection trick_log_visit failed due to: org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI"
org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI"
        at org.apache.solr.client.solrj.impl.CloudSolrClient.directUpdate(CloudSolrClient.java:819)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1263)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1134)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1073)
        at org.apache.solr.client.solrj.SolrClient.request(SolrClient.java:1219)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolr(SolrSupport.scala:329)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:294)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI"
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:610)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:447)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:388)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.lambda$directUpdate$0(CloudSolrClient.java:796)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
        ... 3 more
17/09/22 02:04:57 ERROR Executor: Exception in task 0.0 in stage 5.0 (TID 6)
scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/09/22 02:04:57 WARN TaskSetManager: Lost task 0.0 in stage 5.0 (TID 6, localhost, executor driver): scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

17/09/22 02:04:57 ERROR TaskSetManager: Task 0 in stage 5.0 failed 1 times; aborting job
17/09/22 02:04:57 ERROR CloudSolrClient: Request to collection trick_log_visit failed due to (400) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=9a7be652-c0d5-4add-985f-e1186945bbe1] Error adding field 'config_os_version'='Server 2003' msg=For input string: "Server 2003", retry? 0
17/09/22 02:04:57 ERROR SolrSupport$: Send batch to collection trick_log_visit failed due to: org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=9a7be652-c0d5-4add-985f-e1186945bbe1] Error adding field 'config_os_version'='Server 2003' msg=For input string: "Server 2003"
org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=9a7be652-c0d5-4add-985f-e1186945bbe1] Error adding field 'config_os_version'='Server 2003' msg=For input string: "Server 2003"
        at org.apache.solr.client.solrj.impl.CloudSolrClient.directUpdate(CloudSolrClient.java:819)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1263)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1134)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1073)
        at org.apache.solr.client.solrj.SolrClient.request(SolrClient.java:1219)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolr(SolrSupport.scala:329)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:294)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=9a7be652-c0d5-4add-985f-e1186945bbe1] Error adding field 'config_os_version'='Server 2003' msg=For input string: "Server 2003"
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:610)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:447)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:388)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.lambda$directUpdate$0(CloudSolrClient.java:796)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
        ... 3 more
17/09/22 02:04:57 ERROR Executor: Exception in task 1.0 in stage 5.0 (TID 7)
scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=9a7be652-c0d5-4add-985f-e1186945bbe1] Error adding field 'config_os_version'='Server 2003' msg=For input string: "Server 2003" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/09/22 02:04:57 WARN TaskSetManager: Lost task 1.0 in stage 5.0 (TID 7, localhost, executor driver): scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=9a7be652-c0d5-4add-985f-e1186945bbe1] Error adding field 'config_os_version'='Server 2003' msg=For input string: "Server 2003" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/readwriter.py", line 548, in save
    self._jwrite.save()
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o83.save.
: java.lang.RuntimeException: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 6, localhost, executor driver): scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at solr.DefaultSource.createRelation(DefaultSource.scala:31)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:518)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 6, localhost, executor driver): scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1928)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1941)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1954)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1968)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:924)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:924)
        at com.lucidworks.spark.util.SolrSupport$.indexDocs(SolrSupport.scala:262)
        at com.lucidworks.spark.SolrRelation.insert(SolrRelation.scala:782)
        at solr.DefaultSource.createRelation(DefaultSource.scala:27)
        ... 13 more
Caused by: scala.MatchError: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://instance-2.c.impalacloud111.internal:8983/solr/trick_log_visit_shard1_replica1: ERROR: [doc=dd8e317c-4072-4357-ba5e-6d1493ae854f] Error adding field 'location_region'='HI' msg=For input string: "HI" (of class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException)
        at com.lucidworks.spark.util.SolrSupport$.sendBatchToSolrWithRetry(SolrSupport.scala:298)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:273)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:262)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
```

**Comment by kiranchitturi** [comment]
Could you paste the schema for these tables?

**Comment by cheburakshu** [comment]
>>> parq.printSchema()
root
 |-- idvisit: long (nullable = true)
 |-- idsite: long (nullable = true)
 |-- idvisitor: binary (nullable = true)
 |-- visit_last_action_time: long (nullable = true)
 |-- config_id: binary (nullable = true)
 |-- location_ip: binary (nullable = true)
 |-- user_id: string (nullable = true)
 |-- visit_first_action_time: long (nullable = true)
 |-- visit_goal_buyer: boolean (nullable = true)
 |-- visit_goal_converted: boolean (nullable = true)
 |-- visitor_days_since_first: integer (nullable = true)
 |-- visitor_days_since_order: integer (nullable = true)
 |-- visitor_returning: boolean (nullable = true)
 |-- visitor_count_visits: long (nullable = true)
 |-- visit_entry_idaction_name: long (nullable = true)
 |-- visit_entry_idaction_url: long (nullable = true)
 |-- visit_exit_idaction_name: long (nullable = true)
 |-- visit_exit_idaction_url: long (nullable = true)
 |-- visit_total_actions: long (nullable = true)
 |-- visit_total_interactions: integer (nullable = true)
 |-- visit_total_searches: integer (nullable = true)
 |-- referer_keyword: string (nullable = true)
 |-- referer_name: string (nullable = true)
 |-- referer_type: boolean (nullable = true)
 |-- referer_url: string (nullable = true)
 |-- location_browser_lang: string (nullable = true)
 |-- config_browser_engine: string (nullable = true)
 |-- config_browser_name: string (nullable = true)
 |-- config_browser_version: string (nullable = true)
 |-- config_device_brand: string (nullable = true)
 |-- config_device_model: string (nullable = true)
 |-- config_device_type: integer (nullable = true)
 |-- config_os: string (nullable = true)
 |-- config_os_version: string (nullable = true)
 |-- visit_total_events: long (nullable = true)
 |-- visitor_localtime: long (nullable = true)
 |-- visitor_days_since_last: integer (nullable = true)
 |-- config_resolution: string (nullable = true)
 |-- config_cookie: boolean (nullable = true)
 |-- config_director: boolean (nullable = true)
 |-- config_flash: boolean (nullable = true)
 |-- config_gears: boolean (nullable = true)
 |-- config_java: boolean (nullable = true)
 |-- config_pdf: boolean (nullable = true)
 |-- config_quicktime: boolean (nullable = true)
 |-- config_realplayer: boolean (nullable = true)
 |-- config_silverlight: boolean (nullable = true)
 |-- config_windowsmedia: boolean (nullable = true)
 |-- visit_total_time: long (nullable = true)
 |-- location_city: string (nullable = true)
 |-- location_country: string (nullable = true)
 |-- location_latitude: string (nullable = true)
 |-- location_longitude: string (nullable = true)
 |-- location_region: string (nullable = true)
 |-- custom_var_k1: string (nullable = true)
 |-- custom_var_v1: string (nullable = true)
 |-- custom_var_k2: string (nullable = true)
 |-- custom_var_v2: string (nullable = true)
 |-- custom_var_k3: string (nullable = true)
 |-- custom_var_v3: string (nullable = true)
 |-- custom_var_k4: string (nullable = true)
 |-- custom_var_v4: string (nullable = true)
 |-- custom_var_k5: string (nullable = true)
 |-- custom_var_v5: string (nullable = true)

>>>

**Comment by kiranchitturi** [comment]
Could you look into the Solr logs? It should have more information on the error

It looks like the indexing is failing for value "HI"

**Comment by cheburakshu** [comment]
You are right @kiranchitturi . This is a Apache Solr issue. It is not able to index a document if it has a field name - location_region.

Trying to upload this simple doc fails thru Solr Admin UI. Raising an issue with Solr.

`{"location_region":"test"}`
