### ISSUE TITLE
When using a frange filter, filtering breaks because of no ':'

### ISSUE THREAD

**Issue by MichaelRupertDev** [lucidworks/spark-solr#193]
Using the following config: 
```python
options1 = {'zkhost': zkhosts,
           'collection': 'visit',
           'flatten_multivalued': 'false',
           'splits_per_shard': '1',
           'solr.params': 'fq={!frange l=0 u=0}mod(_version_, 7)'
           }
```
we receive the following error: 
```
: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at com.lucidworks.spark.SolrRelation.filterQueryAsTuple(SolrRelation.scala:612)
        at com.lucidworks.spark.SolrRelation$$anonfun$21.apply(SolrRelation.scala:594)
        at com.lucidworks.spark.SolrRelation$$anonfun$21.apply(SolrRelation.scala:594)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at com.lucidworks.spark.SolrRelation.removeSuperfluousNotNullFilterQuery(SolrRelation.scala:594)
        at com.lucidworks.spark.SolrRelation.buildScan(SolrRelation.scala:490)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:277)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:277)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:321)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:320)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:401)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:316)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:273)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:77)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:74)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:74)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:66)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
        at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
        at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
        at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2832)
        at org.apache.spark.sql.Dataset.head(Dataset.scala:2153)
        at org.apache.spark.sql.Dataset.take(Dataset.scala:2366)
        at org.apache.spark.sql.Dataset.showString(Dataset.scala:245)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
```

After diving into the scala code, I see that all filter queries are fed through a function that parses them into a tuple, splitting on the ':'

This is a valid query and works perfectly in the Solr UI, it should be supported.

**Comment by ariotis** [comment]
For more context, we're trying to better parallelize our queries via splitShards but we're currently using Cloudera's flavor of Solr.  This version of Solr is a bit old (4.x) and doesn't support hash queries like what the connector generates for intra-shard splits (hash workers etc.)

We noticed we were able to get similar results to has partitioning with queries using a frange query and mod.  We were going to initially try to manually create several dataframes, frange/mod filter them, and then union those together, something like:

df1 = df1: fq={!frange l=0 u=0}mod(_version_, 3)
df2 = df2: fq={!frange l=1 u=1}mod(_version_, 3)
df3 = df3: fq={!frange l=2 u=2}mod(_version_, 3)

df = union(df1,df2,df3)

However, after looking at the code, we noticed we might be able to swap out the line where the hash fqs are made with a mod (from the 3.2.x branch since that's the last one that works with Cloudera):

com/lucidworks/spark/util/SolrSupport.scala:636
- val fq = s"{!hash workers=$splitsPerShard worker=$i}"
+ val fq = s"{!frange l=$i u=$i}mod(_version_,$splitsPerShard)"

Can you think of a better way to do this? Using this method, we just set splits_per_shard to however many partitions we want and the mod takes care of it.
