### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.typesafe.scalalogging.LazyLogging

### ISSUE THREAD

**Issue by selmna** [lucidworks/spark-solr#196]
I am using spark 2.2.1 and connector 3.4.0.
spark-shell --packages com.lucidworks.spark:spark-solr:3.4.0 , is not working throwing multiple dependency problem.

::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.apache.spark#spark-tags_2.11;2.0.1!spark-tags_2.11.jar

		:: org.apache.hadoop#hadoop-yarn-server-nodemanager;2.6.0!hadoop-yarn-server-nodemanager.jar

		:: com.google.guava#guava;15.0!guava.jar(bundle)

		::::::::::::::::::::::::::::::::::::::::::::::

:::: ERRORS
	unknown resolver null

	unknown resolver null

	unknown resolver null

	unknown resolver null

	unknown resolver null

	unknown resolver null

	unknown resolver null

	unknown resolver null

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: org.apache.spark#spark-tags_2.11;2.0.1!spark-tags_2.11.jar, download failed: org.apache.hadoop#hadoop-yarn-server-nodemanager;2.6.0!hadoop-yarn-server-nodemanager.jar, download failed: com.google.guava#guava;15.0!guava.jar(bundle)]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1197)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:304)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by selmna** [comment]
i used shaded jar in --jars that works perfect.
