### ISSUE TITLE
Unable to load dataframe

### ISSUE THREAD

**Issue by ankitgaur** [lucidworks/spark-solr#202]
Whenever I try t do this :-

scala> val options = Map("collection" -> "crawl","zkhost" -> "serv1:2181,serv2:2181,serv3:2181")
options: scala.collection.immutable.Map[String,String] = Map(collection -> crawl, zkhost -> serv1:2181,serv2:2181,serv3:2181)

scala> val df = spark.read.format("solr").options(options).load

I get the following error :-

18/03/14 17:18:54 WARN cloud.ConnectionManager: zkClient has disconnected
18/03/14 17:19:01 WARN cloud.ConnectionManager: Watcher org.apache.solr.common.cloud.ConnectionManager@3bc21ddc name: ZooKeeperConnection Watcher:serv1:2181,serv2:2181,serv3:2181 got event WatchedEvent state:Disconnected type:None path:null path: null type: None
18/03/14 17:19:01 WARN cloud.ConnectionManager: zkClient has disconnected
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.solr.common.cloud.ZooKeeperException:
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2234)
  at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)
  at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)
  at com.lucidworks.spark.util.SolrSupport$.getCachedCloudClient(SolrSupport.scala:246)
  at com.lucidworks.spark.util.SolrSupport$.getSolrBaseUrl(SolrSupport.scala:250)
  at com.lucidworks.spark.SolrRelation.dynamicSuffixes$lzycompute(SolrRelation.scala:89)
  at com.lucidworks.spark.SolrRelation.dynamicSuffixes(SolrRelation.scala:87)
  at com.lucidworks.spark.SolrRelation.getBaseSchemaFromConfig(SolrRelation.scala:282)
  at com.lucidworks.spark.SolrRelation.querySchema$lzycompute(SolrRelation.scala:223)
  at com.lucidworks.spark.SolrRelation.querySchema(SolrRelation.scala:97)
  at com.lucidworks.spark.SolrRelation.schema(SolrRelation.scala:411)
  at org.apache.spark.sql.execution.datasources.LogicalRelation$.apply(LogicalRelation.scala:77)
  at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:415)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
  ... 48 elided
Caused by: org.apache.solr.common.cloud.ZooKeeperException:
  at org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider.connect(ZkClientClusterStateProvider.java:165)
  at org.apache.solr.client.solrj.impl.CloudSolrClient.connect(CloudSolrClient.java:397)
  at com.lucidworks.spark.util.SolrSupport$.getSolrCloudClient(SolrSupport.scala:223)
  at com.lucidworks.spark.util.SolrSupport$.getNewSolrCloudClient(SolrSupport.scala:242)
  at com.lucidworks.spark.util.CacheCloudSolrClient$$anon$1.load(SolrSupport.scala:39)
  at com.lucidworks.spark.util.CacheCloudSolrClient$$anon$1.load(SolrSupport.scala:37)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
  ... 63 more
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /clusterstate.json
  at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
  at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
  at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
  at org.apache.solr.common.cloud.SolrZkClient.lambda$exists$3(SolrZkClient.java:315)
  at org.apache.solr.common.cloud.ZkCmdExecutor.retryOperation(ZkCmdExecutor.java:60)
  at org.apache.solr.common.cloud.SolrZkClient.exists(SolrZkClient.java:315)
  at org.apache.solr.common.cloud.ZkStateReader.createClusterStateWatchersAndUpdate(ZkStateReader.java:422)
  at org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider.connect(ZkClientClusterStateProvider.java:156)
  ... 72 more

**Comment by kiranchitturi** [comment]
This seems to be a zookeeper connection loss issue. Please make sure all your zkhost is a valid ensemble
