### ISSUE TITLE
Documentation is not very self explanatory when comes to indexing. No Sample codes 

### ISSUE THREAD

**Issue by appunnicer13** [lucidworks/spark-solr#208]
return df.write.format('solr').option("zkhost", solr_url).save(solr_core)

I am getting error : `Traceback (most recent call last):
  File "/home/dishq-appu/PycharmProjects/fpaas_recommendation/dist/experiments/collab_filter/entry.py", line 43, in process_by_cafetaria
    init(cafetaria_data)
  File "/home/dishq-appu/PycharmProjects/fpaas_recommendation/dist/spark_framework/unloaders/simple_unloader.py", line 31, in decorated
    output = self.writer_engine.write_df(write_data, self.output_key)
  File "/home/dishq-appu/PycharmProjects/fpaas_recommendation/dist/spark_framework/utils/writer_engines/solr_engine.py", line 28, in write_df
    return df.write.format('solr').option("zkhost", self.solr_url).save(solr_core)
  File "/home/dishq-appu/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 703, in save
    self._jwrite.save(path)
  File "/home/dishq-appu/spark/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/dishq-appu/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/dishq-appu/spark/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py", line 320, in get_return_value
    format(target_id, ".", name), value)
Py4JJavaError: An error occurred while calling o724.save.
` 
when trying to index a df. 

spark version : 2.3.0
BTW I am using python, is there support for python ?
Spark-solr : 3.5.0-20180404.155202-9-shaded
Trying it on version 3.4.4 gave me dependency error. #200 

Please fix this for a stable version and can you make a release in Maven.

**Comment by kiranchitturi** [comment]
3.5.0 will be release in a few days with Spark 2.3.0 support. We do not currently have any CI tests with python but it should work. Take a look at any of our tests for indexing examples. Also, https://github.com/lucidworks/spark-solr#indexing

I cannot infer the issue from the code above. Could you format it please? 

You are welcome to make contributions to improve the documentation
