### ISSUE TITLE
pyspark --packages com.lucidworks.spark:spark-solr:2.0.4 gives maven download error

### ISSUE THREAD

**Issue by chirag-orbittec** [lucidworks/spark-solr#209]
Using command 
pyspark --packages option to force maven to download all the dependencies failed.
Gives error:
 module not found: org.restlet.jee#org.restlet;2.3.0

         ==== central: tried

          https://repo1.maven.org/maven2/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom

          -- artifact org.restlet.jee#org.restlet;2.3.0!org.restlet.jar:

          https://repo1.maven.org/maven2/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.pom

          -- artifact org.restlet.jee#org.restlet;2.3.0!org.restlet.jar:

          http://dl.bintray.com/spark-packages/maven/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.jar

                module not found: org.restlet.jee#org.restlet.ext.servlet;2.3.0

           ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.restlet.jee#org.restlet;2.3.0: not found

                :: org.restlet.jee#org.restlet.ext.servlet;2.3.0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::

     :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
     Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: 
     org.restlet.jee#org.restlet;2.3.0: not found, unresolved dependency: 
     org.restlet.jee#org.restlet.ext.servlet;2.3.0: not found]
           at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1075)
           at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:287)
           at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:154)
           at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
           at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
    Traceback (most recent call last):

**Comment by chirag-orbittec** [comment]
@kiranchitturi 
I have not tried shaded jar plus I am using pyspark, I am not sure if I can use pom.xml with that.
For a work around I added this dependency in some other maven project, which downloaded this jars but that had some other problems which made me download the jar manually and I was able to run pyspark code, but I can not do it manually all the time.

Yes I tried and shaded jar worked for me.
Thanks
