### ISSUE TITLE
Getting java.lang.AbstractMethodError while indexing to solr 6.1.0 from spark 1.6

### ISSUE THREAD

**Issue by balakrishnadhanekula** [lucidworks/spark-solr#212]
I am trying to write to Solr 6.1.0 from Spark 1.6

These are the jars in my classpath:
```
spark-assembly-1.6.0-cdh5.13.3-hadoop2.6.0-cdh5.13.3.jar
solr-solrj-6.1.0.jar
hadoop-common-2.6.0-cdh5.13.0.jar
slf4j-api-1.7.5.jar
slf4j-log4j12-1.7.5.jar
log4j-1.2.16.jar
commons-configuration-1.7.jar
hadoop-auth-2.2.0.jar
commons-collections4-4.1.jar
spark-solr-2.2.3-shaded.jar
jersey-server-1.9.jar
hadoop-mapreduce-client-core-2.2.0.jar
jackson-core-2.4.4.jar
jackson-databind-2.4.4.jar
jackson-annotations-2.4.4.jar
snappy-java-1.0.4.1.jar
htrace-core4-4.0.1-incubating.jar
httpclient-4.4.1.jar
httpcore-4.4.1.jar

```

```
Map<String, String> options = new HashMap<>();
options.put("zkhost", zkHost);
options.put("collection", collection);
df.write().format("solr").options(options).mode(SaveMode.Append).save();

```
```
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.AbstractMethodError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at com.lucidworks.spark.util.SolrSupport$.getCachedCloudClient(SolrSupport.scala:93)
	at com.lucidworks.spark.util.SolrSupport$.getSolrBaseUrl(SolrSupport.scala:97)
	at com.lucidworks.spark.util.SolrQuerySupport$.getUniqueKey(SolrQuerySupport.scala:82)
	at com.lucidworks.spark.rdd.SolrRDD.<init>(SolrRDD.scala:32)
	at com.lucidworks.spark.SolrRelation.<init>(SolrRelation.scala:79)
	at solr.DefaultSource.createRelation(DefaultSource.scala:39)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.dataSource$lzycompute$1(DataFrameWriter.scala:181)
	at org.apache.spark.sql.DataFrameWriter.org$apache$spark$sql$DataFrameWriter$$dataSource$1(DataFrameWriter.scala:181)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$save$1.apply$mcV$sp(DataFrameWriter.scala:188)
	at org.apache.spark.sql.DataFrameWriter.executeAndCallQEListener(DataFrameWriter.scala:154)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:188)
	at Test.main(Test.java:57)
Caused by: java.lang.AbstractMethodError
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at com.lucidworks.spark.util.SolrSupport$.log(SolrSupport.scala:59)
	at com.lucidworks.spark.util.SolrSupport$.setupKerberosIfNeeded(SolrSupport.scala:68)
	at com.lucidworks.spark.util.SolrSupport$.getSolrCloudClient(SolrSupport.scala:81)
	at com.lucidworks.spark.util.SolrSupport$.getNewSolrCloudClient(SolrSupport.scala:89)
	at com.lucidworks.spark.util.CacheSolrClient$$anon$1.load(SolrSupport.scala:38)
	at com.lucidworks.spark.util.CacheSolrClient$$anon$1.load(SolrSupport.scala:36)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
	... 16 more
```

**Comment by kiranchitturi** [comment]
I believe this is due to classpath issues with your dependencies. While pulling spark-solr into your own project, please check [pom](https://github.com/lucidworks/spark-solr/blob/2.2.3/pom.xml#L369) and make sure the dependencies and exclusions match

**Comment by balakrishnadhanekula** [comment]
Thanks Kiran. I am able to Index spark data frame to Solr as a stand along job. 
When I run in cloudera cluster I am getting below exception:

```
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    org/apache/solr/client/solrj/impl/HttpClientUtil.createClient(Lorg/apache/solr/common/params/SolrParams;Lorg/apache/http/conn/ClientConnectionManager;)Lorg/apache/http/impl/client/CloseableHttpClient; @58: areturn
  Reason:
    Type 'org/apache/http/impl/client/DefaultHttpClient' (current frame, stack[0]) is not assignable to 'org/apache/http/impl/client/CloseableHttpClient' (from method signature)
  Current Frame:
    bci: @58
    flags: { }
    locals: { 'org/apache/solr/common/params/SolrParams', 'org/apache/http/conn/ClientConnectionManager', 'org/apache/solr/common/params/ModifiableSolrParams', 'org/apache/http/impl/client/DefaultHttpClient' }
    stack: { 'org/apache/http/impl/client/DefaultHttpClient' }
  Bytecode:
    0x0000000: bb00 0359 2ab7 0004 4db2 0005 b900 0601
    0x0000010: 0099 001e b200 05bb 0007 59b7 0008 1209
    0x0000020: b600 0a2c b600 0bb6 000c b900 0d02 002b
    0x0000030: b800 104e 2d2c b800 0f2d b0
  Stackmap Table:
    append_frame(@47,Object[#143])
```
**Cluster Details:**
 Cloudera Express 5.13.0
Solr: 6.1.0
Spark-solr connector - 2.2.3
Spark 1.6.2

**Full error stack attached here:**

[spark_solr_exception.log](https://github.com/lucidworks/spark-solr/files/2032232/spark_solr_exception.log)

**Comment by balakrishnadhanekula** [comment]
any help please.

**Comment by kiranchitturi** [comment]
I do not have much knowledge on the deps used in cloudera but others have faced this issue before I think. Can you search in the issues to see what worked for others who ran into the same issue with cloudera? 

I think it has to do with http client/solr which might have to be excluded while pulling spark-solr
