### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 18: invalid start byte

### ISSUE THREAD

**Issue by rajrohith** [lucidworks/spark-solr#255]
Hi Kiran,
when i try to push the data to solr using write option and job is failed duo to codec issue even i tried many possibilities. please have a look the error and guide me how to proceed further.

+----------------------------------------+--------------------+-----------------------+--------------+--------------------+-------------------------------+-----------------+--------------------------+--------------------+----------------+--------------------+-----------------------+------------------+----------------------+
|xxx|xxxr|createdatetime|createuseridentifier|xxxr| inventornametext|obsoletedocumentidentifier|officeactioncategory|officeactiondate| passagelocationtext|patentapplicationnumber|qualitysummarytext|relatedclaimnumbertext|
+----------------------------------------+--------------------+-----------------------+--------------+--------------------+-------------------------------+-----------------+--------------------------+--------------------+----------------+--------------------+-----------------------+------------------+----------------------+
|                                   false|                   Y|    US 2011/0057454  A1|          null|             ETL_SYS|                           true|Kawakita; Keisuke|           JI1NF47RRXEAPX4|                CTNF|      2018-06-07|""""claim 1 | fig...|               15512682|               AOK|                  1-10|
|                                    true|                   Y|    US 2010/0060015  A1|          null|             ETL_SYS|                           true|            Buker|           JI1NF47RRXEAPX4|                CTNF|      2018-06-07|""""figures 1, 2 ...|               15512682|               AOK|                  1-10|
+----------------------------------------+--------------------+-----------------------+--------------+--------------------+-------------------------------+-----------------+--------------------------+--------------------+----------------+--------------------+-----------------------+------------------+----------------------+
only showing top 2 rows

Traceback (most recent call last):
  File "/data/bdr/scripts/bdr-citation-claim/enriched_cited_reference_metadata_solr_load.py", line 62, in <module>
    loadDF.write.format("solr").option("zkhost",zk_host).option("collection",solr_index).option("batch_size", "10000").option("commit_within", "5000").mode("append").save()
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 494, in option
    self._jwrite = self._jwrite.option(key, to_str(value))
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1124, in __call__
    args_command, temp_args = self._build_args(*args)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1094, in _build_args
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 283, in get_command_part
    command_part = STRING_TYPE + escape_new_line(parameter)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 183, in escape_new_line
    return smart_decode(original).replace("\\", "\\\\").replace("\r", "\\r").\
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 210, in smart_decode
    return unicode(s, "utf-8")
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 18: invalid start byte

**Comment by rajrohith** [comment]
is
