### ISSUE TITLE
org.apache.solr.common.SolrException: Could not find collection

### ISSUE THREAD

**Issue by purohitsumit** [LucidWorks/spark-solr#3]
Hi,
I am trying to run this plugin with sorl5.0.0 running in cloud mode and i get following error.

2015-03-26 13:50:05,859 [Executor task launch worker-0] INFO  ConnectionManager  - Waiting for client to connect to ZooKeeper
2015-03-26 13:50:05,867 [Executor task launch worker-0-SendThread(localhost:9983)] WARN  ClientCnxn  - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2015-03-26 13:50:05,979 [Executor task launch worker-0-EventThread] INFO  ConnectionManager  - Watcher org.apache.solr.common.cloud.ConnectionManager@54b888c2 name:ZooKeeperConnection Watcher:localhost:9983 got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2015-03-26 13:50:05,979 [Executor task launch worker-0] INFO  ConnectionManager  - Client is connected to ZooKeeper
2015-03-26 13:50:05,984 [Executor task launch worker-0] INFO  ZkStateReader  - Updating cluster state from ZooKeeper... 
2015-03-26 13:50:06,005 [Executor task launch worker-0] ERROR SolrSupport  - Send batch to collection testcol failed due to: org.apache.solr.common.SolrException: Could not find collection : testcol
org.apache.solr.common.SolrException: Could not find collection : testcol
	at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:162)
	at org.apache.solr.client.solrj.impl.CloudSolrServer.directUpdate(CloudSolrServer.java:305)
	at org.apache.solr.client.solrj.impl.CloudSolrServer.request(CloudSolrServer.java:533)
	at com.lucidworks.spark.SolrSupport.sendBatchToSolr(SolrSupport.java:188)
	at com.lucidworks.spark.SolrSupport$4.call(SolrSupport.java:170)
	at com.lucidworks.spark.SolrSupport$4.call(SolrSupport.java:160)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:195)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:195)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:773)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:773)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1314)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1314)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-03-26 13:50:06,005 [Executor task launch worker-0] ERROR Executor  - Exception in task 0.0 in stage 6.0 (TID 6)
org.apache.solr.common.SolrException: Could not find collection : testcol
	at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:162)
	at org.apache.solr.client.solrj.impl.CloudSolrServer.directUpdate(CloudSolrServer.java:305)
	at org.apache.solr.client.solrj.impl.CloudSolrServer.request(CloudSolrServer.java:533)
	at com.lucidworks.spark.SolrSupport.sendBatchToSolr(SolrSupport.java:188)
	at com.lucidworks.spark.SolrSupport$4.call(SolrSupport.java:170)
	at com.lucidworks.spark.SolrSupport$4.call(SolrSupport.java:160)

**Comment by kanav-narula** [comment]
I am facing the same issue.  Kindly guide me with the steps to resolve this issue.

**Comment by rashid-1989** [comment]
@purohitsumit were you able to resolve this issue? I am also facing the same exception. Kindly suggest if you could fix it.

Thanks
