### ISSUE TITLE
Accessing collection fails with NullPointerException

### ISSUE THREAD

**Issue by jqnik** [lucidworks/spark-solr#32]
Hi on the current master branch I am running into the following issue, which I did not experience in the 1.1.2 release.

```scala
[vagrant@test550-master spark-solr-master]$ PROJECT_HOME=`pwd` && spark-shell --jars $PROJECT_HOME/target/spark-solr-1.2.0-SNAPSHOT-shaded.jar --driver-class-path $PROJECT_HOME/target/spark-solr-1.2.0-SNAPSHOT-shaded.jar

scala> val poems = sqlContext.load("solr", Map("zkHost" -> "test550-master:2181/solr", "collection" -> "poems"))
warning: there were 1 deprecation warning(s); re-run with -deprecation for details
2016-01-05 14:56:36,987 [main] INFO  SolrZkClient  - Using default ZkCredentialsProvider
2016-01-05 14:56:37,032 [main] INFO  ConnectionManager  - Waiting for client to connect to ZooKeeper
2016-01-05 14:56:37,054 [zkCallback-2-thread-1] INFO  ConnectionManager  - Watcher shaded.apache.solr.common.cloud.ConnectionManager@7d401432 name:ZooKeeperConnection Watcher:test550-master:2181/solr got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2016-01-05 14:56:37,055 [main] INFO  ConnectionManager  - Client is connected to ZooKeeper
2016-01-05 14:56:37,055 [main] INFO  SolrZkClient  - Using default ZkACLProvider
2016-01-05 14:56:37,059 [main] INFO  ZkStateReader  - Updating cluster state from ZooKeeper...
2016-01-05 14:56:37,545 [main] WARN  HiveConf  - HiveConf of name hive.enable.spark.execution.engine does not exist
poems: org.apache.spark.sql.DataFrame = [id: string, text: string, _version_: bigint]

scala> poems.printSchema()
root
 |-- id: string (nullable = false)
 |-- text: string (nullable = false)
 |-- _version_: long (nullable = true)

scala> poems.show()
2016-01-05 14:59:25,856 [main] INFO  SolrRelation  - Building Solr scan using fields=[id, text, _version_]
2016-01-05 14:59:25,857 [main] INFO  SolrRelation  - Constructed SolrQuery: q=*%3A*&rows=1000&sort=id+asc&fl=id%2Ctext%2C_version_&collection=poems
2016-01-05 14:59:29,249 [task-result-getter-0] WARN  TaskSetManager  - Lost task 0.0 in stage 0.0 (TID 0, test550-master.fq.dn): java.lang.RuntimeException: shaded.apache.solr.client.solrj.SolrServerException: java.lang.NullPointerException
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:66)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:215)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: shaded.apache.solr.client.solrj.SolrServerException: java.lang.NullPointerException
	at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:956)
	at com.lucidworks.spark.query.StreamingResultsIterator.fetchNextPage(StreamingResultsIterator.java:91)
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:61)
	... 27 more
Caused by: java.lang.NullPointerException
	at com.lucidworks.spark.SolrRDD.applyFields(SolrRDD.java:622)
	at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:906)
	... 29 more

trying with tempTable:

scala> poems.registerTempTable("poems")

scala> val p = sqlContext.sql("SELECT * from poems")
2016-01-05 15:02:01,588 [main] INFO  ParseDriver  - Parsing command: SELECT * from poems
2016-01-05 15:02:02,286 [main] INFO  ParseDriver  - Parse Completed
p: org.apache.spark.sql.DataFrame = [id: string, text: string, _version_: bigint]

scala> p.show()
2016-01-05 15:02:06,075 [main] INFO  SolrRelation  - Building Solr scan using fields=[id, text, _version_]
2016-01-05 15:02:06,075 [main] INFO  SolrRelation  - Constructed SolrQuery: q=*%3A*&rows=1000&sort=id+asc&fl=id%2Ctext%2C_version_&collection=poems
2016-01-05 15:02:09,242 [task-result-getter-0] WARN  TaskSetManager  - Lost task 0.0 in stage 0.0 (TID 0, test550-master.fq.dn): java.lang.RuntimeException: shaded.apache.solr.client.solrj.SolrServerException: java.lang.NullPointerException
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:66)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:215)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: shaded.apache.solr.client.solrj.SolrServerException: java.lang.NullPointerException
	at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:956)
	at com.lucidworks.spark.query.StreamingResultsIterator.fetchNextPage(StreamingResultsIterator.java:91)
	at com.lucidworks.spark.query.StreamingResultsIterator.hasNext(StreamingResultsIterator.java:61)
	... 27 more
Caused by: java.lang.NullPointerException
	at com.lucidworks.spark.SolrRDD.applyFields(SolrRDD.java:622)
	at com.lucidworks.spark.SolrRDD.querySolr(SolrRDD.java:906)
	... 29 more
```

The same does work with the current 1.1.2 release:

```scala
[vagrant@test550-master spark-solr-1.1.2]$ PROJECT_HOME=`pwd` && spark-shell --jars $PROJECT_HOME/target/spark-solr-1.1.2-shaded.jar --driver-class-path $PROJECT_HOME/target/spark-solr-1.1.2-SNAPSHOT-shaded.jar

scala> val poems = sqlContext.load("solr", Map("zkHost" -> "test550-master:2181/solr", "collection" -> "poems"))
warning: there were 1 deprecation warning(s); re-run with -deprecation for details
poems: org.apache.spark.sql.DataFrame = [_version_: bigint, id: string, text: string]

scala> poems.show()
16/01/05 15:06:35 INFO SolrRelation: Building Solr scan using fields=[_version_, id, text]
16/01/05 15:06:35 INFO SolrRelation: Constructed SolrQuery: q=*%3A*&rows=1000&sort=id+asc&collection=poems&fl=_version_%2Cid%2Ctext
16/01/05 15:06:35 INFO SparkContext: Starting job: show at <console>:22
16/01/05 15:06:35 INFO DAGScheduler: Got job 1 (show at <console>:22) with 1 output partitions
16/01/05 15:06:35 INFO DAGScheduler: Final stage: ResultStage 1(show at <console>:22)
16/01/05 15:06:35 INFO DAGScheduler: Parents of final stage: List()
16/01/05 15:06:35 INFO DAGScheduler: Missing parents: List()
16/01/05 15:06:35 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[9] at show at <console>:22), which has no missing parents
16/01/05 15:06:35 INFO MemoryStore: ensureFreeSpace(3976) called with curMem=6354, maxMem=556038881
16/01/05 15:06:35 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.9 KB, free 530.3 MB)
16/01/05 15:06:35 INFO MemoryStore: ensureFreeSpace(2377) called with curMem=10330, maxMem=556038881
16/01/05 15:06:35 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 2.3 KB, free 530.3 MB)
16/01/05 15:06:35 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.0.0.4:46263 (size: 2.3 KB, free: 530.3 MB)
16/01/05 15:06:35 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:861
16/01/05 15:06:35 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[9] at show at <console>:22)
16/01/05 15:06:35 INFO YarnScheduler: Adding task set 1.0 with 1 tasks
16/01/05 15:06:35 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, test550-master.fq.dn, partition 0,PROCESS_LOCAL, 2145 bytes)
16/01/05 15:06:36 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on test550-master.fq.dn:54886 (size: 2.3 KB, free: 530.3 MB)
16/01/05 15:06:38 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 2365 ms on test550-master.fq.dn (1/1)
16/01/05 15:06:38 INFO YarnScheduler: Removed TaskSet 1.0, whose tasks have all completed, from pool
16/01/05 15:06:38 INFO DAGScheduler: ResultStage 1 (show at <console>:22) finished in 2.366 s
16/01/05 15:06:38 INFO DAGScheduler: Job 1 finished: show at <console>:22, took 2.387781 s
+-------------------+---+--------------------+
|          _version_| id|                text|
+-------------------+---+--------------------+
|1520710855906295808|  1|Mary had a little...|
|1520710855977598976|  2|The quick brown f...|
+-------------------+---+--------------------+


scala>
```

**Comment by kiranchitturi** [comment]
updated your comment with markdown syntax.

**Comment by kiranchitturi** [comment]
@jqnik Could you try with master again ?

We have made a lot of refactoring and bug fixes in the past 2 months.

**Comment by kiranchitturi** [comment]
We are going to make a 2.0.0 release this week. There won't be any 1.x releases
