### ISSUE TITLE
Invocation of AnalysisException uses null in 1.1.2 release

### ISSUE THREAD

**Issue by jqnik** [lucidworks/spark-solr#33]
When constructing a solr query that does not yield any results I run into the following issue with the 1.1.2 shaded jar. I am aware that this section of the code has seen massive changes on the current master, so I don’t know if anyone would consider fixing my issue for the 1.1.2 jar. 

```scala
scala> sqlContext.read.format("solr").option("zkHost", "test550-master:2181/solr").option("collection", "poems2").option("query","text:\"Mary lamb\"~2").load().show()
16/01/05 15:45:58 INFO SolrRelation: before: solrRDD = new SolrRDD(zkHost, collection);
16/01/05 15:45:58 INFO SolrRelation: before: solrQuery = SolrRDD.toQuery(query);
16/01/05 15:45:58 INFO SolrRelation: before: if (fieldList != null) {
16/01/05 15:45:58 INFO SolrRelation: before: if (dataFrame != null) {
16/01/05 15:45:58 INFO SolrRelation: before: schema = solrRDD.getQuerySchema(solrQuery);
java.lang.NullPointerException
	at org.apache.spark.sql.AnalysisException.getMessage(AnalysisException.scala:40)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:391)
	at java.lang.Throwable.toString(Throwable.java:480)
	at java.lang.Throwable.<init>(Throwable.java:311)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at solr.DefaultSource.createRelation(DefaultSource.java:26)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:125)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
```

This is due to code in SolrRDD.java:getQuerySchema where a Spark/Scala AnalysisException is thrown with null parameters. null does not expand to None in Scala, which is expected in the getOrElse method in AnalysisException.scala. For calling Scala Exceptions from Java, one can use scala.Option.apply(null) in Java, which is a bit hacky. But even if we do this, the code will give an ambiguous error indication, which I thrive to fix locally with the patch below. As initially mentioned, I am not sure if anyone would fix this for the current stable release at this point, but reporting nevertheless.

On 2935b32bcb196acb3f70606157619bf4603b9e0e:
```scala
@@ -541,18 +541,24 @@ public class SolrRDD implements Serializable {
       probeForFieldsQuery.set("fl", "*");
       probeForFieldsQuery.setStart(0);
       probeForFieldsQuery.setRows(10);
       QueryResponse probeForFieldsResp = solrServer.query(probeForFieldsQuery);
       SolrDocumentList hits = probeForFieldsResp.getResults();
+      if (hits.getNumFound() < 1) {
+          scala.Option<Object> x = scala.Option.apply(null);
+          throw new AnalysisException("Query ("+query+") does not return any documents from Solr!", x, x);
+      }
       Set<String> fieldSet = new TreeSet<String>();
       for (SolrDocument hit : hits)
         fieldSet.addAll(hit.getFieldNames());
       fields = fieldSet.toArray(new String[0]);
     }
 
-    if (fields == null || fields.length == 0)
-      throw new AnalysisException("Query ("+query+") does not specify any fields needed to build a schema!", null, null);
+    if (fields == null || fields.length == 0) {
+        scala.Option<Object> x = scala.Option.apply(null);
+        throw new AnalysisException("Query ("+query+") does not specify any fields needed to build a schema!", x, x);
+    }
 
     Set<String> liveNodes = solrServer.getZkStateReader().getClusterState().getLiveNodes();
     if (liveNodes.isEmpty())
       throw new RuntimeException("No live nodes found for cluster: "+zkHost);
     String solrBaseUrl = solrServer.getZkStateReader().getBaseUrlForNodeName(liveNodes.iterator().next());
```

**Comment by jqnik** [comment]
Bump on this one... is there a new release slated anytime soon?
Does it make sense to apply a fix to the 1.1.2 release?

**Comment by kiranchitturi** [comment]
@jqnik We are not going to cut another 1.1.x release. The core code has been refactored a lot in the last 2 months. Would you be able to use master for testing ?

We are going to cut 2.0 release soon

**Comment by kiranchitturi** [comment]
@jqnik could you try the 2.0.0 latest release and see how it goes ? Please create a new issue for things related to 2.0.0
