### ISSUE TITLE
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper

### ISSUE THREAD

**Issue by srinvias** [lucidworks/spark-solr#61]
I am using ensemble 3 node zookeeper, getting below error while ruuning hdfs-to-solr example . 

: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to
zookepereper xxxxxx:2181,xxxxxx:2181,xxxxxx:2181 within 10000 ms
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2234)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)
        at com.lucidworks.spark.util.SolrSupport$.getCachedCloudClient(SolrSupport.scala:93)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:153)
        at com.lucidworks.spark.util.SolrSupport$$anonfun$indexDocs$1.apply(SolrSupport.scala:152)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper xxxxxx:2181,xxxxxxx:2181,xxxxxx:2181 within 10000 ms
        at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:179)
        at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:113)
        at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:103)
        at org.apache.solr.common.cloud.ZkStateReader.<init>(ZkStateReader.java:228)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.connect(CloudSolrClient.java:454)
        at com.lucidworks.spark.util.SolrSupport$.getSolrCloudClient(SolrSupport.scala:83)
        at com.lucidworks.spark.util.SolrSupport$.getNewSolrCloudClient(SolrSupport.scala:89)
        at com.lucidworks.spark.util.CacheSolrClient$$anon$1.load(SolrSupport.scala:38)
        at com.lucidworks.spark.util.CacheSolrClient$$anon$1.load(SolrSupport.scala:36)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
        ... 16 more

**Comment by kiranchitturi** [comment]
@srinvias Could you share more information on what you have tried including the full example and logs ?

Did you check to make sure the ZK ensemble is accessible for the spark cluster nodes ?

**Comment by kiranchitturi** [comment]
Closing this issue. Please open a new issue if you are still facing problems
