### ISSUE TITLE
spark-solr Kerberos support

### ISSUE THREAD

**Issue by risdenk** [lucidworks/spark-solr#79]
Looks like there are 2 issues with Kerberos support:

1) SolrSupport setupKerberosIfNeeded method logic isn't correct
https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/util/SolrSupport.scala#L66

```java
       if (configurer.get.isInstanceOf[Krb5HttpClientConfigurer]) {
```

should be

```java
       if (!configurer.get.isInstanceOf[Krb5HttpClientConfigurer]) {
```

2) SolrJsonSupport getHttpClient method doesn't setup Kerberos
https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/util/SolrJsonSupport.scala#L164

I think it should have a SolrSupport.setupKerberosIfNeeded() call
```java
def getHttpClient(): HttpClient = {
    SolrSupport.setupKerberosIfNeeded()

    val params = new ModifiableSolrParams()
```

I can open a PR if either of these fixes make sense.

**Comment by risdenk** [comment]
Without these, this seems to cause issues getting the schema information: 

```
2016-07-20 16:06:07,571 WARN  [Driver] util.SolrQuerySupport: Can't get uniqueKey for COLLECTION due to solr: org.apache.solr.common.SolrException: Request [https://HOSTNAME:8983/solr/COLLECTION/schema?wt=json] failed due to: HTTP/1.1 401 Authentication required: <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><title>Error 401 Authentication required</title></head><body><h2>HTTP ERROR 401</h2><p>Problem accessing /solr/COLLECTION/schema. Reason:<pre>    Authentication required</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/></body></html>
2016-07-20 16:06:07,587 ERROR [Driver] util.SolrQuerySupport: Can't get field type metadata from Solr url https://HOSTNAME:8983/solr/COLLECTION/schema/fieldtypes
2016-07-20 16:06:07,589 ERROR [Driver] yarn.ApplicationMaster: User class threw exception: org.apache.solr.common.SolrException: Request [https://HOSTNAME:8983/solr/COLLECTION/schema/fieldtypes?wt=json] failed due to: HTTP/1.1 401 Authentication required: <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><title>Error 401 Authentication required</title></head><body><h2>HTTP ERROR 401</h2><p>Problem accessing /solr/COLLECTION/schema/fieldtypes. Reason:<pre>    Authentication required</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/></body></html>
org.apache.solr.common.SolrException: Request [https://HOSTNAME:8983/solr/COLLECTION/schema/fieldtypes?wt=json] failed due to: HTTP/1.1 401 Authentication required: <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><title>Error 401 Authentication required</title></head><body><h2>HTTP ERROR 401</h2><p>Problem accessing /solr/COLLECTION/schema/fieldtypes. Reason:<pre>    Authentication required</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/></body></html>
	at com.lucidworks.spark.util.SolrJsonSupport$.doJsonRequest(SolrJsonSupport.scala:92)
	at com.lucidworks.spark.util.SolrJsonSupport$.getJson(SolrJsonSupport.scala:73)
	at com.lucidworks.spark.util.SolrJsonSupport$.getJson(SolrJsonSupport.scala:34)
	at com.lucidworks.spark.util.SolrQuerySupport$.getFieldTypeToClassMap(SolrQuerySupport.scala:474)
	at com.lucidworks.spark.util.SolrQuerySupport$.getFieldTypes(SolrQuerySupport.scala:258)
	at com.lucidworks.spark.util.SolrQuerySupport$.getFieldTypes(SolrQuerySupport.scala:254)
	at com.lucidworks.spark.util.SolrRelationUtil$.getBaseSchema(SolrRelationUtil.scala:35)
	at com.lucidworks.spark.SolrRelation.<init>(SolrRelation.scala:83)
	at solr.DefaultSource.createRelation(DefaultSource.scala:26)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:529)
```

**Comment by thelabdude** [comment]
Good find, I'll fix. Thanks!

**Comment by risdenk** [comment]
@thelabdude awesome thanks!

**Comment by risdenk** [comment]
@thelabdude anything I can do to help?

**Comment by thelabdude** [comment]
sorry for the delay, have a few more things that are higher priority. should be this week though ... PR's always welcome ;-)
