### ISSUE TITLE
NoSuchMethodError: org.apache.solr.client.solrj.SolrQuery.toQueryString()Ljava/lang/String;

### ISSUE THREAD

**Issue by theDalecious1** [lucidworks/spark-solr#84]
Lucidworks Spark-Solr version 2.0.4 in pom, but drops to 2.0.1
Java version 1.8
Spark version 1.6.1
Solr version 5.5.2
Scala Binary version 2.10

and I am thinking it is a version issue. The previous step comes from com.lucidworks.spark.query.SolrStreamIterator.hasNext(SolrStreamIterator).

**Comment by kiranchitturi** [comment]
@theDalecious1 Can you post the full stacktrace ?

Do you have any other versions of Solr in your application ?

**Comment by theDalecious1** [comment]
@kiranchitturi Here is the full stacktrace

java.lang.NoSuchMethodError: org.apache.solr.client.solrj.SolrQuery.toQueryString()Ljava/lang/String;
	at com.lucidworks.spark.query.SolrStreamIterator.hasNext(SolrStreamIterator.java:96) ~[spark-solr-2.0.1.jar:na]
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41) ~[scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327) ~[scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388) ~[scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327) ~[scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327) ~[scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308) ~[scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48) ~[scala-library-2.10.4.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103) ~[scala-library-2.10.4.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47) ~[scala-library-2.10.4.jar:na]
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273) ~[scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.to(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265) ~[scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252) ~[scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$28.apply(RDD.scala:1328) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$28.apply(RDD.scala:1328) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:89) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214) ~[spark-core_2.10-1.6.1.jar:1.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

We are also using Solr 5.3.1

**Comment by kiranchitturi** [comment]
yeah, looks like the SolrParams#toQueryString is introduced in 5.4.x Solr and the library is using it.

Since your application is on 5.3.1, 2.0.x series won't work.

To make the library work with 5.3.1, you have to fork the library and compile with 5.3.1  or update SolrJ in your application to 5.5.1

**Comment by theDalecious1** [comment]
Kiran,

Updating SolrJ to 5.5.x seems to have worked. 

Thank you

**Comment by theDalecious1** [comment]
After fixing the logging statement issue, I ran into another issue where I believe that solr cannot parse a JSONTupleStream (SolrDocument, essentially) correctly. After running a SolrQuery on a cloud collection, I try and generate tf-idf vectors from fields in solr. However, SolrJ is expecting the object to begin with a left curly brace (JSONParser.OBJECT_START, but finds String instead.

Java 1.8, Spark 1.6.1, Solr 5.5.2 (only version), Scala binary 2.10

Stacktrace:

java.io.IOException: JSONTupleStream: expected OBJECT_START but got STRING
	at org.apache.solr.client.solrj.io.stream.JSONTupleStream.expect(JSONTupleStream.java:98) ~[solr-solrj-5.5.2.jar:5.5.2 8e5d40b22a3968df065dfc078ef81cbb031f0e4a - sarowe - 2016-06-21 11:44:13]
	at org.apache.solr.client.solrj.io.stream.JSONTupleStream.advanceToDocs(JSONTupleStream.java:156) ~[solr-solrj-5.5.2.jar:5.5.2 8e5d40b22a3968df065dfc078ef81cbb031f0e4a - sarowe - 2016-06-21 11:44:13]
	at org.apache.solr.client.solrj.io.stream.JSONTupleStream.next(JSONTupleStream.java:76) ~[solr-solrj-5.5.2.jar:5.5.2 8e5d40b22a3968df065dfc078ef81cbb031f0e4a - sarowe - 2016-06-21 11:44:13]
	at org.apache.solr.client.solrj.io.stream.SolrStream.read(SolrStream.java:147) ~[solr-solrj-5.5.2.jar:5.5.2 8e5d40b22a3968df065dfc078ef81cbb031f0e4a - sarowe - 2016-06-21 11:44:13]
	at com.lucidworks.spark.query.SolrStreamIterator.fetchNextDocument(SolrStreamIterator.java:115) ~[spark-solr-2.0.4.jar:na]
	at com.lucidworks.spark.query.SolrStreamIterator.hasNext(SolrStreamIterator.java:93) ~[spark-solr-2.0.4.jar:na]
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41) [scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327) [scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388) [scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327) [scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327) [scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308) [scala-library-2.10.4.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) [scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [scala-library-2.10.4.jar:na]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48) [scala-library-2.10.4.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103) [scala-library-2.10.4.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47) [scala-library-2.10.4.jar:na]
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273) [scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.to(Iterator.scala:1157) [scala-library-2.10.4.jar:na]
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265) [scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157) [scala-library-2.10.4.jar:na]
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252) [scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157) [scala-library-2.10.4.jar:na]
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$28.apply(RDD.scala:1328) [spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$28.apply(RDD.scala:1328) [spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858) [spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858) [spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66) [spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:89) [spark-core_2.10-1.6.1.jar:1.6.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214) [spark-core_2.10-1.6.1.jar:1.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by kiranchitturi** [comment]
@theDalecious1 Could you share with me the code that is making the query ?

**Comment by theDalecious1** [comment]
Here is the code for the query. We took it from an older iteration of a lucidworks spark-solr example. The SolrVectorProcessor works in a similar fashion as lucidworks spark-solr did: executes a query and iterates through the results.
The CobraVector is just a wrapper around the mllib.regression.LabeledPoint: double array with indicies, a field for classification. CobraVector just has another field so we can keep track of every document's unique ID.

com.lucidworks....SolrRDD solrRDD = new SolrRDD(
				flowFile.getAttribute("zkhosts"),
				initValues.get("collection"),
				jsc.sc(),
				exportHandler, null, fields, null, splitField, splitsPerShard, null);
com.lucidworks...SolrJavaRDD solrJavaRDD = new SolrJavaRDD(solrRDD);
SolrQuery query = new SolrQuery(classifierField+":*");
query.addSort(SolrQuery.SortClause.asc(Constants.SOLR_GUID_FIELD));
		query.setFields(new String[]{ Constants.SOLR_GUID_FIELD, solrVectorParams });
		query.setParam("tv.tf,value_idf", true);
		query.setRows(2000);
JavaRDD<CobraVector>[] comboRDD = solrJavaRDD.queryShards(query).map((doc) -> makeVecs(processor, doc, classifierField, solrVectorFields, limit, blocksize)).randomSplit(doubleSplits);

// makeVecs method
private static CobraVector makeVecs(NiFiSolrVectorProcessor processor, SolrDocument doc, String classifierField, String solrVectorFields, Integer limit, Integer blocksize) throws SparkException, IOException, SolrServerException {
		String guid = (String) doc.getFieldValue(Constants.SOLR_GUID_FIELD);
		CobraVector cv = processor.vec4Guid(guid, solrVectorFields, classifierField, limit, blocksize);
		String vd = (String) doc.getFieldValue(classifierField);
		cv.vectorClass = vd.equalsIgnoreCase("yes")?1:0;
		return cv;
	}

public CobraVector vec4Guid(String guid, String solrVectorFields, String classifierField, Integer limit, Integer blocksize) throws IOException, SolrServerException {
		SolrQuery solrQuery = makeQuery("guid:"+guid, solrVectorFields, classifierField, limit, blocksize);
		QueryResponse guids = server.query(solrQuery);
		List<CobraVector> vectors = processQueryResponse(guids, solrVectorFields, classifierField);
		return vectors!=null&&vectors.size()>0?vectors.get(0):null;
	}

private List<CobraVector> processQueryResponse(QueryResponse resp, String solrVectorFields, String classifierField) {
		NamedList<Object> response = resp.getResponse();
		
		NamedList<Object> termVectorsNL = (NamedList<Object>) response.get("termVectors");
		if (termVectorsNL == null) {
			logger.error("No term vectors, ignoring...");
			return null;
		}
		
		List<CobraVector> termVectors = new ArrayList<>(termVectorsNL.size());
		Iterator<Map.Entry<String, Object>> iter = termVectorsNL.iterator();
		while (iter.hasNext()) {
			Map.Entry<String, Object> next = iter.next();
			String nextKey = next.getKey();
			Object nextValue = next.getValue();
			
			ArrayList<NamedList<Object>> fieldTermsList = new ArrayList<>();
			if (nextValue instanceof NamedList) {
				NamedList<Object> nextList = (NamedList<Object>) nextValue;
				for (String field : solrVectorFields.split(",")) {
					Object fieldTerms = nextList.get(field);
					if (fieldTerms != null && fieldTerms instanceof NamedList) {
						fieldTermsList.add((NamedList<Object>) fieldTerms);
					}
				}
				Integer vclass = getVectorClass(resp, nextKey, classifierField);
				termVectors.add(CobraVector.makeVector(nextKey, vclass, hashingTF, fieldTermsList));
			}
		}
		return termVectors;
	}

**Comment by kiranchitturi** [comment]
@theDalecious1  

In here, what is the value of the exportHandler ? Set it to `false`

```
SolrRDD solrRDD = new SolrRDD(flowFile.getAttribute("zkhosts"),initValues.get("collection"),jsc.sc(),exportHandler, null, fields, null, splitField, splitsPerShard, null);
```

**Comment by theDalecious1** [comment]
@kiranchitturi 

I believe I found the problem. Instead of wrapping SolrJavaRDD around SolrRDD, I am using the static method SolrJavaRDD.get(...) and it fixed my issues.

Thank you for your help. You may close this thread.

**Comment by kiranchitturi** [comment]
cool. Thanks!
