### ISSUE TITLE
Using spark-solr with scala 2.11

### ISSUE THREAD

**Issue by arpitrathore** [lucidworks/spark-solr#91]
I am using spark with scala 2.11 and trying to read data from solr but it says spark-solr is compiled with scala 2.10. How to compile spark-solr with scala 2.11?

**Comment by kiranchitturi** [comment]
@arpitrathore All the spark-solr artifacts are generated against 2.10 because Spark by default (until 1.6.x) generated artifacts against 2.10.x. The next release of spark-solr (Spark 2.0.1) will be with 2.11

You can fork the repo and build spark-solr artifacts against scala 2.11. Let me know if you run into any issues there.

**Comment by arpitrathore** [comment]
When compiling with spark 2.11.0, I am getting this error-

[INFO] Compiling 26 Scala sources and 30 Java sources to /home/arathore/git/spark-solr/target/classes...
[ERROR] /home/arathore/git/spark-solr/src/main/scala/com/lucidworks/spark/ml/feature/LuceneTextAnalyzerTransformer.scala:129: No TypeTag available for Seq[String]
[ERROR]     val analysisFunc = udf { row: Row =>
[ERROR]                            ^
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.958s
[INFO] Finished at: Thu Nov 03 12:05:07 IST 2016
[INFO] Final Memory: 43M/846M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project spark-solr: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project spark-solr: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: Compilation failed
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:105)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:48)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:99)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:99)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:99)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:166)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:98)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:143)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:87)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:39)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:37)
	at sbt.inc.IncrementalCommon.cycle(Incremental.scala:99)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:37)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:65)
	at sbt.inc.Incremental$.compile(Incremental.scala:37)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:27)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:157)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:71)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:184)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:164)
	at sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:92)
	at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:303)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:119)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by kiranchitturi** [comment]
What branch are you using here? Did you make any changes to pom.xml ?

**Comment by arpitrathore** [comment]
Yes. I am trying to compile spark-solr with Scala 2.11 for Spark1.6

**Comment by arpitrathore** [comment]
I am using branch 2.0.0

Changed made in pom.xml - 
<scala.version>2.11.0</scala.version>

**Comment by kiranchitturi** [comment]
@arpitrathore you have to change both `scala.version` and `scala.binary.version` https://github.com/lucidworks/spark-solr/blob/2.2.2/pom.xml#L43

I recommend using the 2.2.2 branch (Since it is the latest branch against 1.6.x). You might have to fix few compile bugs that will come with 2.11 scala version

**Comment by arpitrathore** [comment]
After doing above changes, I am getting this error (We are using Java 7)

[ERROR] javac: invalid source release: 1.8
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options

**Comment by kiranchitturi** [comment]
you have to change it here https://github.com/lucidworks/spark-solr/blob/2.2.2/pom.xml#L39
