### ISSUE TITLE
error: bad symbolic reference.

### ISSUE THREAD

**Issue by leninlal** [lucidworks/spark-solr#96]
Hi everyone, 
i'm getting this error on spark scala shell.

```
scala> import com.lucidworks.spark.rdd.SolrRDD
import com.lucidworks.spark.rdd.SolrRDD

scala> val s = new SolrRDD("192.168.1.102:2181", "collection", sc)

error: bad symbolic reference. A signature in SolrRDD.class refers to term solr
in package org.apache which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling SolrRDD.class.
<console>:28: error: bad symbolic reference. A signature in SolrRDD.class refers to term common
in value org.apache.solr which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling SolrRDD.class.
         val s = new SolrRDD("192.168.1.102:2181", "collection", sc)
```

i've built the package from source using 
 `mvn clean package -DskipTests`
build process completed successfully and created jar file in target directory.

Basically i'm not a scala person, so is there any API's available in pyspark ? and what are the version compatibilities ?

**Comment by kiranchitturi** [comment]
@leninlal which jar file are you adding to the spark-shell ? Instead of spark-solr-{version}.jar can you try the spark-solr-{version}-shaded.jar ?

The master (latest and 3.0.x) works with Solr 6.2.1 and Spark 2.0.1

The branch 2.2.2 (and 2.x.x releases) work with Spark 1.6.x and Solr 6.1.0.

We have plans on adding a compatibility graph. I will try to add something soon

It is possible to use pyspark to access the DataFrames. I haven't worked on this much but I just tried an example

```
Kirans-MacBook-Pro:spark-2.0.1-bin-hadoop2.6 kiran$ ./bin/pyspark --jars ~/Git/spark-solr/target/spark-solr-3.0.0-alpha.1-shaded.jar --master spark://Kirans-MacBook-Pro.local:7077
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
2016-11-02 10:47:14,266 [Thread-2] WARN  NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-11-02 10:47:14,301 [Thread-2] WARN  Utils  - Your hostname, Kirans-MacBook-Pro.local resolves to a loopback address: 127.0.0.1; using 10.0.0.42 instead (on interface en0)
2016-11-02 10:47:14,301 [Thread-2] WARN  Utils  - Set SPARK_LOCAL_IP if you need to bind to another address
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.0.1
      /_/

Using Python version 2.7.10 (default, Oct 23 2015 19:19:21)
SparkSession available as 'spark'.
>>> df = spark.read.format("solr").options(zkhost="localhost:9987", collection="eventsim").load()
2016-11-02 10:47:33,630 [Thread-2] WARN  ObjectStore  - Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
2016-11-02 10:47:33,700 [Thread-2] WARN  ObjectStore  - Failed to get database default, returning NoSuchObjectException
2016-11-02 10:47:34,267 [Thread-2] ERROR RetryingHMSHandler  - AlreadyExistsException(message:Database default already exists)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.create_database(HiveMetaStore.java:891)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:107)
	at com.sun.proxy.$Proxy14.create_database(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createDatabase(HiveMetaStoreClient.java:644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:156)
	at com.sun.proxy.$Proxy15.createDatabase(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.createDatabase(Hive.java:306)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$createDatabase$1.apply$mcV$sp(HiveClientImpl.scala:309)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$createDatabase$1.apply(HiveClientImpl.scala:309)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$createDatabase$1.apply(HiveClientImpl.scala:309)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:280)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:227)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:226)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:269)
	at org.apache.spark.sql.hive.client.HiveClientImpl.createDatabase(HiveClientImpl.scala:308)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createDatabase$1.apply$mcV$sp(HiveExternalCatalog.scala:99)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createDatabase$1.apply(HiveExternalCatalog.scala:99)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createDatabase$1.apply(HiveExternalCatalog.scala:99)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:72)
	at org.apache.spark.sql.hive.HiveExternalCatalog.createDatabase(HiveExternalCatalog.scala:98)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createDatabase(SessionCatalog.scala:147)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.<init>(SessionCatalog.scala:89)
	at org.apache.spark.sql.hive.HiveSessionCatalog.<init>(HiveSessionCatalog.scala:51)
	at org.apache.spark.sql.hive.HiveSessionState.catalog$lzycompute(HiveSessionState.scala:49)
	at org.apache.spark.sql.hive.HiveSessionState.catalog(HiveSessionState.scala:48)
	at org.apache.spark.sql.hive.HiveSessionState$$anon$1.<init>(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer$lzycompute(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer(HiveSessionState.scala:62)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:382)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:143)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

>>> df.show()
+------+--------------------+--------------------+----+----------+---------+--------------------+--------------------+---------+-----------+--------------------+-------------+------+------+---------+------+-------------------+--------------------+------+------+-----+
|method|     _indexed_at_tdt|            location|song|      auth|     page|                  ts|           userAgent| lastName|  firstName|                  id|itemInSession|artist|status|sessionId|length|          _version_|        registration|userId|gender|level|
+------+--------------------+--------------------+----+----------+---------+--------------------+--------------------+---------+-----------+--------------------+-------------+------+------+---------+------+-------------------+--------------------+------+------+-----+
|   GET|2016-10-08 19:05:...|    York-Hanover, PA|null| Logged In|     Home|2015-05-31 18:55:...|"Mozilla/5.0 (X11...|     West|      Kalik|6f310392-8275-4de...|            0|  null|   200|      161|   0.0|1547675870816108544|2015-05-30 14:03:...|    88|     M| paid|
|   GET|2016-10-08 19:05:...|Austin-Round Rock...|null| Logged In|     Home|2015-06-01 00:43:...|Mozilla/5.0 (Wind...|   Flores|   Emmanuel|5b41dd26-0c85-46c...|            0|  null|   200|      141|   0.0|1547675870859100160|2015-05-30 23:56:...|    56|     M| free|
|   GET|2016-10-08 19:05:...|Austin-Round Rock...|null| Logged In|     Home|2015-06-01 00:47:...|Mozilla/5.0 (Wind...|   Flores|   Emmanuel|68ed62f9-3860-41e...|            2|  null|   200|      141|   0.0|1547675870860148736|2015-05-30 23:56:...|    56|     M| free|
|   GET|2016-10-08 19:05:...|Hermiston-Pendlet...|null| Logged In|    About|2015-06-01 03:44:...|"Mozilla/5.0 (Win...|     Howe|       Reid|764c4f3a-b406-4e2...|            7|  null|   200|       60|   0.0|1547675870877974528|2015-05-25 09:01:...|    61|     M| free|
|   GET|2016-10-08 19:05:...|                null|null|Logged Out|     Home|2015-06-01 06:31:...|                null|     null|       null|0cbead5e-f55d-4cd...|            0|  null|   200|      164|   0.0|1547675870884265984|1969-12-31 16:00:...|  null|  null| paid|
|   GET|2016-10-08 19:05:...|Phoenix-Mesa-Scot...|null| Logged In|     Home|2015-06-01 08:25:...|"Mozilla/5.0 (Win...|   Garcia|Christopher|ce064232-e7d6-474...|            0|  null|   200|      137|   0.0|1547675870891606016|2015-05-28 05:44:...|    57|     M| free|
|   GET|2016-10-08 19:05:...|Phoenix-Mesa-Scot...|null| Logged In|    About|2015-06-01 08:25:...|"Mozilla/5.0 (Win...|   Garcia|Christopher|03449d35-c6a9-4bc...|            1|  null|   200|      137|   0.0|1547675870892654592|2015-05-28 05:44:...|    57|     M| free|
|   GET|2016-10-08 19:05:...|Hermiston-Pendlet...|null| Logged In|     Home|2015-06-01 11:56:...|"Mozilla/5.0 (Win...|     Howe|       Reid|95c02f75-b099-4a5...|            0|  null|   200|      179|   0.0|1547675870908383232|2015-05-25 09:01:...|    61|     M| free|
|   GET|2016-10-08 19:05:...|    York-Hanover, PA|null| Logged In|     Home|2015-06-01 13:03:...|"Mozilla/5.0 (X11...|     West|      Kalik|ded1739a-0bb4-43f...|            0|  null|   200|      171|   0.0|1547675870911528960|2015-05-30 14:03:...|    88|     M| paid|
|   GET|2016-10-08 19:05:...|Harrisburg-Carlis...|null| Logged In|     Home|2015-06-01 19:49:...|"Mozilla/5.0 (Mac...| Arellano|      Kevin|6eb66a59-000e-49c...|            0|  null|   200|      178|   0.0|1547675870918868992|2015-05-19 00:50:...|    65|     M| free|
|   GET|2016-10-08 19:05:...|Austin-Round Rock...|null| Logged In|     Home|2015-06-01 21:07:...|Mozilla/5.0 (Wind...|   Flores|   Emmanuel|b145b62a-447e-467...|            0|  null|   200|      175|   0.0|1547675870919917568|2015-05-30 23:56:...|    56|     M| free|
|   GET|2016-10-08 19:05:...|Los Angeles-Long ...|null| Logged In|     Home|2015-06-01 23:29:...|"Mozilla/5.0 (Mac...|     Peck|       Raul|f7cde1ae-fa6f-4f2...|            0|  null|   200|      180|   0.0|1547675870924111872|2015-05-31 00:05:...|    91|     M| free|
|   GET|2016-10-08 19:05:...|Los Angeles-Long ...|null| Logged In|     Home|2015-06-02 05:46:...|"Mozilla/5.0 (Win...|   Garcia|      Riley|249c3249-aa94-412...|            0|  null|   200|      177|   0.0|1547675870928306177|2015-05-31 06:48:...|    79|     F| free|
|   GET|2016-10-08 19:05:...|Los Angeles-Long ...|null| Logged In|     Home|2015-06-02 06:10:...|"Mozilla/5.0 (Win...|  Roberts|       Luke|13826988-3f00-47d...|            0|  null|   200|       59|   0.0|1547675870929354752|2015-05-31 14:54:...|    60|     M| free|
|   GET|2016-10-08 19:05:...|Little Rock-North...|null| Logged In|     Home|2015-06-02 06:30:...|"Mozilla/5.0 (Mac...|    Lyons|     Jayden|0df2dc37-c89a-438...|            0|  null|   200|      207|   0.0|1547675870931451904|2015-05-31 08:54:...|    69|     M| free|
|   GET|2016-10-08 19:05:...|Denver-Aurora-Lak...|null| Logged In|     Home|2015-06-02 08:07:...|Mozilla/5.0 (Wind...|   Garcia|     Sydney|e08be413-075c-418...|            0|  null|   200|      170|   0.0|1547675870940889088|2015-05-31 07:11:...|    68|     F| free|
|   GET|2016-10-08 19:05:...|    St. Louis, MO-IL|null| Logged In|     Home|2015-06-02 09:26:...|"Mozilla/5.0 (X11...|   Taylor|      Molly|7faef9f6-cc87-447...|            0|  null|   200|      166|   0.0|1547675870950326272|2015-05-30 10:41:...|    36|     F| free|
|   GET|2016-10-08 19:05:...|    York-Hanover, PA|null| Logged In|     Home|2015-06-02 10:43:...|"Mozilla/5.0 (X11...|     West|      Kalik|04f6bf84-5291-4e8...|           14|  null|   200|      196|   0.0|1547675870973394944|2015-05-30 14:03:...|    88|     M| paid|
|   GET|2016-10-08 19:05:...|Brownsville-Harli...|null| Logged In|Downgrade|2015-06-02 18:34:...|"Mozilla/5.0 (Mac...|   Lester|     Damien|17b0fba4-0f39-424...|            8|  null|   200|       92|   0.0|1547675871003803648|2015-05-27 00:30:...|    93|     M| paid|
|   GET|2016-10-08 19:05:...|          Duncan, OK|null| Logged In|     Home|2015-06-02 22:05:...|"Mozilla/5.0 (Win...|Maldonado|     Steven|d2090518-bc5f-41b...|           15|  null|   200|       17|   0.0|1547675871018483713|2015-05-31 07:20:...|    18|     M| paid|
+------+--------------------+--------------------+----+----------+---------+--------------------+--------------------+---------+-----------+--------------------+-------------+------+------+---------+------+-------------------+--------------------+------+------+-----+
only showing top 20 rows

>>> 
```

**Comment by leninlal** [comment]
@kiranchitturi  , thanks , it works

**Comment by mohnihal** [comment]
@kiranchitturi 
I have tried with pyspark but getting an error 
```
f = spark.read.format("solr").options(zkhost="192.168.1.102:2181", collection="gettingstarted").load()

In [2]: f
Out[2]: DataFrame[name: string, url: string, country: string, id: string, _version_: bigint]

In [3]: f.show()
2016-11-03 16:05:26,225 [Executor task launch worker-0] ERROR TupleStreamIterator  - Failed to fetch next Tuple for query: ?q=*%3A*&collection=gettingstarted&fl=name%2Curl%2Ccountry%2Cid%2C_version_&sort=name+asc&qt=%2Fexport&distrib=false
java.io.IOException: --> http://192.168.1.105:8983/solr/gettingstarted_shard1_replica1/:can not sort on multivalued field: name
	at org.apache.solr.client.solrj.io.stream.SolrStream.read(SolrStream.java:228)
	at com.lucidworks.spark.query.TupleStreamIterator.fetchNextTuple(TupleStreamIterator.java:81)
	at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:46)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Also , getting same error using spark-shell
```

scala> val options = Map(
     |   "collection" -> "gettingstarted",
     |   "zkhost" -> "192.168.1.102:2181"
     | )
options: scala.collection.immutable.Map[String,String] = Map(collection -> gettingstarted, zkhost -> 192.168.1.102:2181)
scala> val df = spark.read.format("solr").options(options).load
scala> df.show()
2016-11-03 16:38:17,368 [Executor task launch worker-0] ERROR TupleStreamIterator  - Failed to fetch next Tuple for query: ?q=*%3A*&collection=gettingstarted&fl=name%2Curl%2Ccountry%2Cid%2C_version_&sort=name+asc&qt=%2Fexport&distrib=false
java.io.IOException: --> http://192.168.1.105:8983/solr/gettingstarted_shard1_replica1/:can not sort on multivalued field: name
	at org.apache.solr.client.solrj.io.stream.SolrStream.read(SolrStream.java:228)
	at com.lucidworks.spark.query.TupleStreamIterator.fetchNextTuple(TupleStreamIterator.java:81)
	at com.lucidworks.spark.query.TupleStreamIterator.hasNext(TupleStreamIterator.java:46)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-11-03 16:38:17,378 [Executor task launch worker-0] ERROR Executor  - Exception in task 0.0 in stage 0.0 (TID 0)



```

**Comment by kiranchitturi** [comment]
@mohnihal Which version of spark-solr are you using in this example ? Thought I fixed this bug

Can you try adding a sort param in the options `solr.params -> "sort= id asc"` and see if it fixes the issue ?

**Comment by mohnihal** [comment]
@kiranchitturi 
Thanks. So I tried with 
`scala> val df = spark.read.format("solr").options(options).option("solr.params", "sort=id desc").load`
and it seems to work 

```
scala> df.show()
+--------------------+--------------------+------------------+--------------------+-------------------+
|                name|                 url|           country|                  id|          _version_|
+--------------------+--------------------+------------------+--------------------+-------------------+
|Çetinler Sağlık L...|https://www.example...|            Turkey|061ef8fa-849d-4cf...|1549947411555680256|
|      北京悦信瑞通软件技术有限公司|https://www.example...|             China|1339fe1d-dc33-47a...|1549947411788464128|
|Тренинговый центр...|https://www.example...|              null|146b0ad0-621b-42d...|1549947411613351936|
|Кадровый центр Do...|https://www.example...|              null|15a12200-b2e3-46c...|1549947411596574720|
|Туристическая ком...|https://www.example...|              null|16479009-b39d-457...|1549947411614400512|
|    Årets banktjänst|https://www.example...|              null|190ba2da-996a-486...|1549947411553583104|
|Персональное решение|https://www.example...|Russian Federation|1a2ce163-755c-42c...|1549947411611254784|
|        上海奕行信息科技有限公司|https://www.example...|             China|22adadb3-5ccf-48a...|1549947411619643392|
|            北京京科肝泰医院|https://www.example...|              null|2c47f0a7-52f4-403...|1549947411786366976|
|   Люмакс Инжиниринг|https://www.example...|           Ukraine|2efd6ee6-44a3-448...|1549947411599720448|
|   Önel Dişli Sanayi|https://www.example...|            Turkey|378b5cc4-455b-4ce...|1549947411566166016|
|                 БКТ|https://www.example...|              null|3cf1c8e1-61ed-43f...|1549947411585040384|
|    Монитор Здоровья|https://www.example...|              null|3fb1d414-fa36-45f...|1549947411602866176|
|  Özdemir Oto Market|https://www.example...|            Turkey|41a20680-2fd5-428...|1549947411570360320|
|Джей-Промо (J-Promo)|https://www.example...|           Belarus|44129843-dcc0-4ab...|1549947411592380416|
|Strong Cedar Trad...|https://www.example...|              null|4503cb72-ef55-44d...|1549947411616497664|
|             ライザップ上海|https://www.example...|              null|4d5cd013-51f2-466...|1549947411617546241|
|      ТракСтрой, ООО|https://www.example...|Russian Federation|52537d11-8cff-455...|1549947411611254785|
|      北京未来码头网络技术有限公司|https://www.example...|             China|54d16e9c-83d7-490...|1549947411788464129|
|         北京九识佳科技有限公司|https://www.example...|             China|5a9b9d00-4dfe-4b0...|1549947411785318400|
+--------------------+--------------------+------------------+--------------------+-------------------+
only showing top 20 rows
```
