### ISSUE TITLE
2016-11-26 14:20:16,050 [main] WARN  SolrQuerySupport  - Can't get uniqueKey for collection1 due to: java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by hafizmujadid** [lucidworks/spark-solr#99]
Hi, I am using following piece of code to write to solr using dataframe api as follow.

`val writeoptions = scala.collection.immutable.HashMap(
			"zkhost" -> "192.168.23.109:2181",
			"collection" -> "collection1",
			"soft_commit_secs" -> "10")
		df.write.format("solr").options(writeoptions).mode(SaveMode.Overwrite).save`
But it returns following error.

`2016-11-26 14:20:16,050 [main] WARN  SolrQuerySupport  - Can't get uniqueKey for collection1 due to: java.net.ConnectException: Connection refused: connect
2016-11-26 14:20:20,108 [main] ERROR SolrQuerySupport  - Can't get field type metadata from Solr url http://127.0.1.1:8983/solr/collection1/schema/fieldtypes
Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
	at com.lucidworks.spark.util.SolrQuerySupport$.getFieldTypeToClassMap(SolrQuerySupport.scala:506)
	at com.lucidworks.spark.util.SolrQuerySupport$.getFieldTypes(SolrQuerySupport.scala:258)
	at com.lucidworks.spark.util.SolrQuerySupport$.getFieldTypes(SolrQuerySupport.scala:254)
	at com.lucidworks.spark.util.SolrRelationUtil$.getBaseSchema(SolrRelationUtil.scala:35)
	at com.lucidworks.spark.SolrRelation.<init>(SolrRelation.scala:83)
	at solr.DefaultSource.createRelation(DefaultSource.scala:26)`
Why it is connecting to 127.0.0.1?  Do I need to create collection before writing data into it?

**Comment by kiranchitturi** [comment]
yes, the collection needs to be created before the data gets written to it.

spark-solr gets the Solr node information from zookeeper `live_nodes`

**Comment by hafizmujadid** [comment]
But why it is connecting to 127.0.0.1? any suggestions?

**Comment by kiranchitturi** [comment]
This is more of a Solr issue. We get the Solr urls from SolrJ client which gets the addresses from Zookeeper
